/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EpistemicLedgerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addAnchor"
      | "anchors"
      | "currentValidatorCount"
      | "evidence"
      | "evidenceExists"
      | "getAnchorCount"
      | "getEvidenceCount"
      | "governanceRules"
      | "hasValidatorConsensus"
      | "proofExists"
      | "recordEvidence"
      | "registerValidatorConsensus"
      | "sovereign"
      | "transferSovereignty"
      | "updateGovernanceRule"
      | "validatorConsensusTarget"
      | "verifyProof"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AnchorAdded"
      | "EvidenceRecorded"
      | "GovernanceRuleUpdated"
      | "ValidatorConsensusReached"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addAnchor",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "anchors",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "currentValidatorCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "evidence",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "evidenceExists",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAnchorCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEvidenceCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "governanceRules",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "hasValidatorConsensus",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "proofExists", values: [string]): string;
  encodeFunctionData(
    functionFragment: "recordEvidence",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerValidatorConsensus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "sovereign", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferSovereignty",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateGovernanceRule",
    values: [string, string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "validatorConsensusTarget",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verifyProof",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "addAnchor", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "anchors", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "currentValidatorCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "evidence", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "evidenceExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAnchorCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEvidenceCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "governanceRules",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasValidatorConsensus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proofExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordEvidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerValidatorConsensus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sovereign", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferSovereignty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateGovernanceRule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validatorConsensusTarget",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyProof",
    data: BytesLike
  ): Result;
}

export namespace AnchorAddedEvent {
  export type InputTuple = [
    proofId: string,
    contentHash: string,
    timestamp: BigNumberish,
    submitter: AddressLike
  ];
  export type OutputTuple = [
    proofId: string,
    contentHash: string,
    timestamp: bigint,
    submitter: string
  ];
  export interface OutputObject {
    proofId: string;
    contentHash: string;
    timestamp: bigint;
    submitter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EvidenceRecordedEvent {
  export type InputTuple = [
    evidenceId: string,
    sourceHash: string,
    timestamp: BigNumberish,
    recorder: AddressLike
  ];
  export type OutputTuple = [
    evidenceId: string,
    sourceHash: string,
    timestamp: bigint,
    recorder: string
  ];
  export interface OutputObject {
    evidenceId: string;
    sourceHash: string;
    timestamp: bigint;
    recorder: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GovernanceRuleUpdatedEvent {
  export type InputTuple = [ruleId: string, name: string, active: boolean];
  export type OutputTuple = [ruleId: string, name: string, active: boolean];
  export interface OutputObject {
    ruleId: string;
    name: string;
    active: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidatorConsensusReachedEvent {
  export type InputTuple = [
    validatorCount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [validatorCount: bigint, timestamp: bigint];
  export interface OutputObject {
    validatorCount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EpistemicLedger extends BaseContract {
  connect(runner?: ContractRunner | null): EpistemicLedger;
  waitForDeployment(): Promise<this>;

  interface: EpistemicLedgerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addAnchor: TypedContractMethod<
    [proofId: string, contentHash: string],
    [void],
    "nonpayable"
  >;

  anchors: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, string, boolean] & {
        proofId: string;
        contentHash: string;
        timestamp: bigint;
        submitter: string;
        verified: boolean;
      }
    ],
    "view"
  >;

  currentValidatorCount: TypedContractMethod<[], [bigint], "view">;

  evidence: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, string] & {
        evidenceId: string;
        sourceHash: string;
        timestamp: bigint;
        recorder: string;
      }
    ],
    "view"
  >;

  evidenceExists: TypedContractMethod<[arg0: string], [boolean], "view">;

  getAnchorCount: TypedContractMethod<[], [bigint], "view">;

  getEvidenceCount: TypedContractMethod<[], [bigint], "view">;

  governanceRules: TypedContractMethod<
    [arg0: string],
    [
      [string, string, boolean, bigint] & {
        ruleId: string;
        name: string;
        active: boolean;
        lastUpdated: bigint;
      }
    ],
    "view"
  >;

  hasValidatorConsensus: TypedContractMethod<[], [boolean], "view">;

  proofExists: TypedContractMethod<[arg0: string], [boolean], "view">;

  recordEvidence: TypedContractMethod<
    [evidenceId: string, sourceHash: string],
    [void],
    "nonpayable"
  >;

  registerValidatorConsensus: TypedContractMethod<
    [validatorCount: BigNumberish],
    [void],
    "nonpayable"
  >;

  sovereign: TypedContractMethod<[], [string], "view">;

  transferSovereignty: TypedContractMethod<
    [newSovereign: AddressLike],
    [void],
    "nonpayable"
  >;

  updateGovernanceRule: TypedContractMethod<
    [ruleId: string, name: string, active: boolean],
    [void],
    "nonpayable"
  >;

  validatorConsensusTarget: TypedContractMethod<[], [bigint], "view">;

  verifyProof: TypedContractMethod<[index: BigNumberish], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addAnchor"
  ): TypedContractMethod<
    [proofId: string, contentHash: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "anchors"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, string, boolean] & {
        proofId: string;
        contentHash: string;
        timestamp: bigint;
        submitter: string;
        verified: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "currentValidatorCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "evidence"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, string] & {
        evidenceId: string;
        sourceHash: string;
        timestamp: bigint;
        recorder: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "evidenceExists"
  ): TypedContractMethod<[arg0: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "getAnchorCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEvidenceCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "governanceRules"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, boolean, bigint] & {
        ruleId: string;
        name: string;
        active: boolean;
        lastUpdated: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasValidatorConsensus"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "proofExists"
  ): TypedContractMethod<[arg0: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "recordEvidence"
  ): TypedContractMethod<
    [evidenceId: string, sourceHash: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerValidatorConsensus"
  ): TypedContractMethod<[validatorCount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sovereign"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferSovereignty"
  ): TypedContractMethod<[newSovereign: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateGovernanceRule"
  ): TypedContractMethod<
    [ruleId: string, name: string, active: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "validatorConsensusTarget"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "verifyProof"
  ): TypedContractMethod<[index: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "AnchorAdded"
  ): TypedContractEvent<
    AnchorAddedEvent.InputTuple,
    AnchorAddedEvent.OutputTuple,
    AnchorAddedEvent.OutputObject
  >;
  getEvent(
    key: "EvidenceRecorded"
  ): TypedContractEvent<
    EvidenceRecordedEvent.InputTuple,
    EvidenceRecordedEvent.OutputTuple,
    EvidenceRecordedEvent.OutputObject
  >;
  getEvent(
    key: "GovernanceRuleUpdated"
  ): TypedContractEvent<
    GovernanceRuleUpdatedEvent.InputTuple,
    GovernanceRuleUpdatedEvent.OutputTuple,
    GovernanceRuleUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ValidatorConsensusReached"
  ): TypedContractEvent<
    ValidatorConsensusReachedEvent.InputTuple,
    ValidatorConsensusReachedEvent.OutputTuple,
    ValidatorConsensusReachedEvent.OutputObject
  >;

  filters: {
    "AnchorAdded(string,string,uint256,address)": TypedContractEvent<
      AnchorAddedEvent.InputTuple,
      AnchorAddedEvent.OutputTuple,
      AnchorAddedEvent.OutputObject
    >;
    AnchorAdded: TypedContractEvent<
      AnchorAddedEvent.InputTuple,
      AnchorAddedEvent.OutputTuple,
      AnchorAddedEvent.OutputObject
    >;

    "EvidenceRecorded(string,string,uint256,address)": TypedContractEvent<
      EvidenceRecordedEvent.InputTuple,
      EvidenceRecordedEvent.OutputTuple,
      EvidenceRecordedEvent.OutputObject
    >;
    EvidenceRecorded: TypedContractEvent<
      EvidenceRecordedEvent.InputTuple,
      EvidenceRecordedEvent.OutputTuple,
      EvidenceRecordedEvent.OutputObject
    >;

    "GovernanceRuleUpdated(string,string,bool)": TypedContractEvent<
      GovernanceRuleUpdatedEvent.InputTuple,
      GovernanceRuleUpdatedEvent.OutputTuple,
      GovernanceRuleUpdatedEvent.OutputObject
    >;
    GovernanceRuleUpdated: TypedContractEvent<
      GovernanceRuleUpdatedEvent.InputTuple,
      GovernanceRuleUpdatedEvent.OutputTuple,
      GovernanceRuleUpdatedEvent.OutputObject
    >;

    "ValidatorConsensusReached(uint256,uint256)": TypedContractEvent<
      ValidatorConsensusReachedEvent.InputTuple,
      ValidatorConsensusReachedEvent.OutputTuple,
      ValidatorConsensusReachedEvent.OutputObject
    >;
    ValidatorConsensusReached: TypedContractEvent<
      ValidatorConsensusReachedEvent.InputTuple,
      ValidatorConsensusReachedEvent.OutputTuple,
      ValidatorConsensusReachedEvent.OutputObject
    >;
  };
}
