/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ValoraiplusSovereignScript {
  export type PresentationExhibitStruct = {
    sectionTitle: string;
    contentHash: string;
    truthCycle: BigNumberish;
    latched: boolean;
  };

  export type PresentationExhibitStructOutput = [
    sectionTitle: string,
    contentHash: string,
    truthCycle: bigint,
    latched: boolean
  ] & {
    sectionTitle: string;
    contentHash: string;
    truthCycle: bigint;
    latched: boolean;
  };
}

export interface ValoraiplusSovereignScriptInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "MERKLEROOT_SAINT_PAUL"
      | "SOVEREIGN_AUDITOR_ROLE"
      | "SYSTEM_FINALITY"
      | "TRUTH_CYCLE_MS"
      | "checkExhibitState"
      | "eip712Domain"
      | "getAestheticManifest"
      | "getEngineManifest"
      | "getEvidenceManifest"
      | "getFinalityManifest"
      | "getIntroManifest"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "latchPresentationStep"
      | "renounceRole"
      | "revokeRole"
      | "sealProjectCinema"
      | "supportsInterface"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EIP712DomainChanged"
      | "ExhibitLatched"
      | "FinalitySealed"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MERKLEROOT_SAINT_PAUL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SOVEREIGN_AUDITOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SYSTEM_FINALITY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TRUTH_CYCLE_MS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "checkExhibitState",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "eip712Domain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAestheticManifest",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEngineManifest",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEvidenceManifest",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFinalityManifest",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getIntroManifest",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "latchPresentationStep",
    values: [BigNumberish, string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sealProjectCinema",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MERKLEROOT_SAINT_PAUL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SOVEREIGN_AUDITOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SYSTEM_FINALITY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TRUTH_CYCLE_MS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkExhibitState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eip712Domain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAestheticManifest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEngineManifest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEvidenceManifest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFinalityManifest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getIntroManifest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "latchPresentationStep",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sealProjectCinema",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
}

export namespace EIP712DomainChangedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExhibitLatchedEvent {
  export type InputTuple = [
    section: BigNumberish,
    title: string,
    cycle: BigNumberish
  ];
  export type OutputTuple = [section: bigint, title: string, cycle: bigint];
  export interface OutputObject {
    section: bigint;
    title: string;
    cycle: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FinalitySealedEvent {
  export type InputTuple = [message: string, merkleroot: BytesLike];
  export type OutputTuple = [message: string, merkleroot: string];
  export interface OutputObject {
    message: string;
    merkleroot: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ValoraiplusSovereignScript extends BaseContract {
  connect(runner?: ContractRunner | null): ValoraiplusSovereignScript;
  waitForDeployment(): Promise<this>;

  interface: ValoraiplusSovereignScriptInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  MERKLEROOT_SAINT_PAUL: TypedContractMethod<[], [string], "view">;

  SOVEREIGN_AUDITOR_ROLE: TypedContractMethod<[], [string], "view">;

  SYSTEM_FINALITY: TypedContractMethod<[], [string], "view">;

  TRUTH_CYCLE_MS: TypedContractMethod<[], [bigint], "view">;

  checkExhibitState: TypedContractMethod<
    [section: BigNumberish],
    [ValoraiplusSovereignScript.PresentationExhibitStructOutput],
    "view"
  >;

  eip712Domain: TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;

  getAestheticManifest: TypedContractMethod<[], [string], "view">;

  getEngineManifest: TypedContractMethod<[], [string], "view">;

  getEvidenceManifest: TypedContractMethod<[], [string], "view">;

  getFinalityManifest: TypedContractMethod<[], [string], "view">;

  getIntroManifest: TypedContractMethod<[], [string], "view">;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  latchPresentationStep: TypedContractMethod<
    [
      sectionIndex: BigNumberish,
      logicHash: string,
      cycle: BigNumberish,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  sealProjectCinema: TypedContractMethod<[], [void], "nonpayable">;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MERKLEROOT_SAINT_PAUL"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "SOVEREIGN_AUDITOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "SYSTEM_FINALITY"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "TRUTH_CYCLE_MS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "checkExhibitState"
  ): TypedContractMethod<
    [section: BigNumberish],
    [ValoraiplusSovereignScript.PresentationExhibitStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "eip712Domain"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAestheticManifest"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getEngineManifest"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getEvidenceManifest"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getFinalityManifest"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getIntroManifest"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "latchPresentationStep"
  ): TypedContractMethod<
    [
      sectionIndex: BigNumberish,
      logicHash: string,
      cycle: BigNumberish,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sealProjectCinema"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;

  getEvent(
    key: "EIP712DomainChanged"
  ): TypedContractEvent<
    EIP712DomainChangedEvent.InputTuple,
    EIP712DomainChangedEvent.OutputTuple,
    EIP712DomainChangedEvent.OutputObject
  >;
  getEvent(
    key: "ExhibitLatched"
  ): TypedContractEvent<
    ExhibitLatchedEvent.InputTuple,
    ExhibitLatchedEvent.OutputTuple,
    ExhibitLatchedEvent.OutputObject
  >;
  getEvent(
    key: "FinalitySealed"
  ): TypedContractEvent<
    FinalitySealedEvent.InputTuple,
    FinalitySealedEvent.OutputTuple,
    FinalitySealedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;

  filters: {
    "EIP712DomainChanged()": TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;
    EIP712DomainChanged: TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;

    "ExhibitLatched(uint256,string,uint256)": TypedContractEvent<
      ExhibitLatchedEvent.InputTuple,
      ExhibitLatchedEvent.OutputTuple,
      ExhibitLatchedEvent.OutputObject
    >;
    ExhibitLatched: TypedContractEvent<
      ExhibitLatchedEvent.InputTuple,
      ExhibitLatchedEvent.OutputTuple,
      ExhibitLatchedEvent.OutputObject
    >;

    "FinalitySealed(string,bytes32)": TypedContractEvent<
      FinalitySealedEvent.InputTuple,
      FinalitySealedEvent.OutputTuple,
      FinalitySealedEvent.OutputObject
    >;
    FinalitySealed: TypedContractEvent<
      FinalitySealedEvent.InputTuple,
      FinalitySealedEvent.OutputTuple,
      FinalitySealedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
  };
}
