/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface VALORAIPLUS_NULL_GHOSTInterface extends Interface {
  getFunction(
    nameOrSignature: "get_root" | "verify_standing"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "get_root", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verify_standing",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "get_root", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verify_standing",
    data: BytesLike
  ): Result;
}

export interface VALORAIPLUS_NULL_GHOST extends BaseContract {
  connect(runner?: ContractRunner | null): VALORAIPLUS_NULL_GHOST;
  waitForDeployment(): Promise<this>;

  interface: VALORAIPLUS_NULL_GHOSTInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  get_root: TypedContractMethod<[], [string], "view">;

  verify_standing: TypedContractMethod<
    [node_hash: BytesLike],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "get_root"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verify_standing"
  ): TypedContractMethod<[node_hash: BytesLike], [string], "view">;

  filters: {};
}
