/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ValorToken__factory } from "./ValorToken__factory";
export { ValorTokenFactory__factory } from "./ValorTokenFactory__factory";
