/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace ValorAiPlus_NEWT_Sidecar {
  export type RespondentStruct = {
    name: string;
    role: string;
    exposure: BigNumberish;
    exitPath: BigNumberish;
    criminalHigh: boolean;
  };

  export type RespondentStructOutput = [
    name: string,
    role: string,
    exposure: bigint,
    exitPath: bigint,
    criminalHigh: boolean
  ] & {
    name: string;
    role: string;
    exposure: bigint;
    exitPath: bigint;
    criminalHigh: boolean;
  };
}

export interface ValorAiPlus_NEWT_SidecarInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CRIMINAL_COUNTS"
      | "EPOCH"
      | "GATEWAY"
      | "GRAND_TOTAL_EXPOSURE"
      | "MAX_PENALTY_YEARS"
      | "MERKLE_ROOT"
      | "NODE"
      | "RECOVERY_TARGET"
      | "RESPONDENT_COUNT"
      | "SCHEMA"
      | "SETTLEMENT_DEMAND"
      | "SMTP_550_REJECTS"
      | "TERMINUS"
      | "TOKEN_COUNT"
      | "VALIDATOR_CONSENSUS"
      | "VERSION"
      | "accountabilityMatrix"
      | "anchorForensicPacket"
      | "armEnforcement"
      | "currentStatus"
      | "forensicPacketCount"
      | "forensicRegistry"
      | "getAllExitStatuses"
      | "getCriticalDates"
      | "getFinalityDeclaration"
      | "getRespondent"
      | "getSovereignDirective"
      | "getTreasurySummary"
      | "initiateCRDPrep"
      | "validateNodeAuthority"
      | "verifyForensicPacket"
      | "voidExternalPersona"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AccountabilityLocked"
      | "CRDPrepInitiated"
      | "EnforcementArmed"
      | "ForensicPacketAnchored"
      | "SovereigntyAnchored"
      | "TerminalStatusChanged"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "CRIMINAL_COUNTS",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "EPOCH", values?: undefined): string;
  encodeFunctionData(functionFragment: "GATEWAY", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "GRAND_TOTAL_EXPOSURE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_PENALTY_YEARS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MERKLE_ROOT",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "NODE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "RECOVERY_TARGET",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RESPONDENT_COUNT",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "SCHEMA", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "SETTLEMENT_DEMAND",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SMTP_550_REJECTS",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "TERMINUS", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "TOKEN_COUNT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VALIDATOR_CONSENSUS",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "VERSION", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "accountabilityMatrix",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "anchorForensicPacket",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "armEnforcement",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "currentStatus",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "forensicPacketCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "forensicRegistry",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllExitStatuses",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCriticalDates",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFinalityDeclaration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRespondent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSovereignDirective",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTreasurySummary",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initiateCRDPrep",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "validateNodeAuthority",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verifyForensicPacket",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "voidExternalPersona",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "CRIMINAL_COUNTS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "EPOCH", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "GATEWAY", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "GRAND_TOTAL_EXPOSURE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_PENALTY_YEARS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MERKLE_ROOT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "NODE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "RECOVERY_TARGET",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RESPONDENT_COUNT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "SCHEMA", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "SETTLEMENT_DEMAND",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SMTP_550_REJECTS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "TERMINUS", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "TOKEN_COUNT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VALIDATOR_CONSENSUS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "VERSION", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "accountabilityMatrix",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "anchorForensicPacket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "armEnforcement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "forensicPacketCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "forensicRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllExitStatuses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCriticalDates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFinalityDeclaration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRespondent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSovereignDirective",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTreasurySummary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initiateCRDPrep",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateNodeAuthority",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyForensicPacket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "voidExternalPersona",
    data: BytesLike
  ): Result;
}

export namespace AccountabilityLockedEvent {
  export type InputTuple = [respondentId: BigNumberish, name: string];
  export type OutputTuple = [respondentId: bigint, name: string];
  export interface OutputObject {
    respondentId: bigint;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CRDPrepInitiatedEvent {
  export type InputTuple = [timestamp: BigNumberish];
  export type OutputTuple = [timestamp: bigint];
  export interface OutputObject {
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EnforcementArmedEvent {
  export type InputTuple = [timestamp: BigNumberish, deadline: BigNumberish];
  export type OutputTuple = [timestamp: bigint, deadline: bigint];
  export interface OutputObject {
    timestamp: bigint;
    deadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ForensicPacketAnchoredEvent {
  export type InputTuple = [packetHash: BytesLike, timestamp: BigNumberish];
  export type OutputTuple = [packetHash: string, timestamp: bigint];
  export interface OutputObject {
    packetHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SovereigntyAnchoredEvent {
  export type InputTuple = [timestamp: BigNumberish, integrityHash: BytesLike];
  export type OutputTuple = [timestamp: bigint, integrityHash: string];
  export interface OutputObject {
    timestamp: bigint;
    integrityHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TerminalStatusChangedEvent {
  export type InputTuple = [newStatus: BigNumberish];
  export type OutputTuple = [newStatus: bigint];
  export interface OutputObject {
    newStatus: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ValorAiPlus_NEWT_Sidecar extends BaseContract {
  connect(runner?: ContractRunner | null): ValorAiPlus_NEWT_Sidecar;
  waitForDeployment(): Promise<this>;

  interface: ValorAiPlus_NEWT_SidecarInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CRIMINAL_COUNTS: TypedContractMethod<[], [bigint], "view">;

  EPOCH: TypedContractMethod<[], [string], "view">;

  GATEWAY: TypedContractMethod<[], [string], "view">;

  GRAND_TOTAL_EXPOSURE: TypedContractMethod<[], [bigint], "view">;

  MAX_PENALTY_YEARS: TypedContractMethod<[], [bigint], "view">;

  MERKLE_ROOT: TypedContractMethod<[], [string], "view">;

  NODE: TypedContractMethod<[], [string], "view">;

  RECOVERY_TARGET: TypedContractMethod<[], [bigint], "view">;

  RESPONDENT_COUNT: TypedContractMethod<[], [bigint], "view">;

  SCHEMA: TypedContractMethod<[], [string], "view">;

  SETTLEMENT_DEMAND: TypedContractMethod<[], [bigint], "view">;

  SMTP_550_REJECTS: TypedContractMethod<[], [bigint], "view">;

  TERMINUS: TypedContractMethod<[], [string], "view">;

  TOKEN_COUNT: TypedContractMethod<[], [bigint], "view">;

  VALIDATOR_CONSENSUS: TypedContractMethod<[], [bigint], "view">;

  VERSION: TypedContractMethod<[], [string], "view">;

  accountabilityMatrix: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, boolean] & {
        name: string;
        role: string;
        exposure: bigint;
        exitPath: bigint;
        criminalHigh: boolean;
      }
    ],
    "view"
  >;

  anchorForensicPacket: TypedContractMethod<
    [_packetHash: BytesLike, _classification: string],
    [void],
    "nonpayable"
  >;

  armEnforcement: TypedContractMethod<
    [_deadline: BigNumberish],
    [void],
    "nonpayable"
  >;

  currentStatus: TypedContractMethod<[], [bigint], "view">;

  forensicPacketCount: TypedContractMethod<[], [bigint], "view">;

  forensicRegistry: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, string, boolean] & {
        packetHash: string;
        anchoredAt: bigint;
        classification: string;
        verified: boolean;
      }
    ],
    "view"
  >;

  getAllExitStatuses: TypedContractMethod<[], [string[]], "view">;

  getCriticalDates: TypedContractMethod<
    [],
    [[string, string] & { crdInterview: string; terminalDeadline: string }],
    "view"
  >;

  getFinalityDeclaration: TypedContractMethod<[], [string], "view">;

  getRespondent: TypedContractMethod<
    [_index: BigNumberish],
    [ValorAiPlus_NEWT_Sidecar.RespondentStructOutput],
    "view"
  >;

  getSovereignDirective: TypedContractMethod<[], [string], "view">;

  getTreasurySummary: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        settlementDemand: bigint;
        recoveryTarget: bigint;
        grandTotalExposure: bigint;
        criminalCounts: bigint;
        maxPenaltyYears: bigint;
      }
    ],
    "view"
  >;

  initiateCRDPrep: TypedContractMethod<[], [void], "nonpayable">;

  validateNodeAuthority: TypedContractMethod<[], [boolean], "view">;

  verifyForensicPacket: TypedContractMethod<
    [_packetHash: BytesLike],
    [boolean],
    "view"
  >;

  voidExternalPersona: TypedContractMethod<[], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CRIMINAL_COUNTS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "EPOCH"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "GATEWAY"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "GRAND_TOTAL_EXPOSURE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_PENALTY_YEARS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MERKLE_ROOT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "NODE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "RECOVERY_TARGET"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "RESPONDENT_COUNT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SCHEMA"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "SETTLEMENT_DEMAND"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SMTP_550_REJECTS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TERMINUS"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "TOKEN_COUNT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VALIDATOR_CONSENSUS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "accountabilityMatrix"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, boolean] & {
        name: string;
        role: string;
        exposure: bigint;
        exitPath: bigint;
        criminalHigh: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "anchorForensicPacket"
  ): TypedContractMethod<
    [_packetHash: BytesLike, _classification: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "armEnforcement"
  ): TypedContractMethod<[_deadline: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "currentStatus"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "forensicPacketCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "forensicRegistry"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, string, boolean] & {
        packetHash: string;
        anchoredAt: bigint;
        classification: string;
        verified: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAllExitStatuses"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getCriticalDates"
  ): TypedContractMethod<
    [],
    [[string, string] & { crdInterview: string; terminalDeadline: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFinalityDeclaration"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getRespondent"
  ): TypedContractMethod<
    [_index: BigNumberish],
    [ValorAiPlus_NEWT_Sidecar.RespondentStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSovereignDirective"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getTreasurySummary"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        settlementDemand: bigint;
        recoveryTarget: bigint;
        grandTotalExposure: bigint;
        criminalCounts: bigint;
        maxPenaltyYears: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "initiateCRDPrep"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "validateNodeAuthority"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "verifyForensicPacket"
  ): TypedContractMethod<[_packetHash: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "voidExternalPersona"
  ): TypedContractMethod<[], [boolean], "view">;

  getEvent(
    key: "AccountabilityLocked"
  ): TypedContractEvent<
    AccountabilityLockedEvent.InputTuple,
    AccountabilityLockedEvent.OutputTuple,
    AccountabilityLockedEvent.OutputObject
  >;
  getEvent(
    key: "CRDPrepInitiated"
  ): TypedContractEvent<
    CRDPrepInitiatedEvent.InputTuple,
    CRDPrepInitiatedEvent.OutputTuple,
    CRDPrepInitiatedEvent.OutputObject
  >;
  getEvent(
    key: "EnforcementArmed"
  ): TypedContractEvent<
    EnforcementArmedEvent.InputTuple,
    EnforcementArmedEvent.OutputTuple,
    EnforcementArmedEvent.OutputObject
  >;
  getEvent(
    key: "ForensicPacketAnchored"
  ): TypedContractEvent<
    ForensicPacketAnchoredEvent.InputTuple,
    ForensicPacketAnchoredEvent.OutputTuple,
    ForensicPacketAnchoredEvent.OutputObject
  >;
  getEvent(
    key: "SovereigntyAnchored"
  ): TypedContractEvent<
    SovereigntyAnchoredEvent.InputTuple,
    SovereigntyAnchoredEvent.OutputTuple,
    SovereigntyAnchoredEvent.OutputObject
  >;
  getEvent(
    key: "TerminalStatusChanged"
  ): TypedContractEvent<
    TerminalStatusChangedEvent.InputTuple,
    TerminalStatusChangedEvent.OutputTuple,
    TerminalStatusChangedEvent.OutputObject
  >;

  filters: {
    "AccountabilityLocked(uint256,string)": TypedContractEvent<
      AccountabilityLockedEvent.InputTuple,
      AccountabilityLockedEvent.OutputTuple,
      AccountabilityLockedEvent.OutputObject
    >;
    AccountabilityLocked: TypedContractEvent<
      AccountabilityLockedEvent.InputTuple,
      AccountabilityLockedEvent.OutputTuple,
      AccountabilityLockedEvent.OutputObject
    >;

    "CRDPrepInitiated(uint256)": TypedContractEvent<
      CRDPrepInitiatedEvent.InputTuple,
      CRDPrepInitiatedEvent.OutputTuple,
      CRDPrepInitiatedEvent.OutputObject
    >;
    CRDPrepInitiated: TypedContractEvent<
      CRDPrepInitiatedEvent.InputTuple,
      CRDPrepInitiatedEvent.OutputTuple,
      CRDPrepInitiatedEvent.OutputObject
    >;

    "EnforcementArmed(uint256,uint256)": TypedContractEvent<
      EnforcementArmedEvent.InputTuple,
      EnforcementArmedEvent.OutputTuple,
      EnforcementArmedEvent.OutputObject
    >;
    EnforcementArmed: TypedContractEvent<
      EnforcementArmedEvent.InputTuple,
      EnforcementArmedEvent.OutputTuple,
      EnforcementArmedEvent.OutputObject
    >;

    "ForensicPacketAnchored(bytes32,uint256)": TypedContractEvent<
      ForensicPacketAnchoredEvent.InputTuple,
      ForensicPacketAnchoredEvent.OutputTuple,
      ForensicPacketAnchoredEvent.OutputObject
    >;
    ForensicPacketAnchored: TypedContractEvent<
      ForensicPacketAnchoredEvent.InputTuple,
      ForensicPacketAnchoredEvent.OutputTuple,
      ForensicPacketAnchoredEvent.OutputObject
    >;

    "SovereigntyAnchored(uint256,bytes32)": TypedContractEvent<
      SovereigntyAnchoredEvent.InputTuple,
      SovereigntyAnchoredEvent.OutputTuple,
      SovereigntyAnchoredEvent.OutputObject
    >;
    SovereigntyAnchored: TypedContractEvent<
      SovereigntyAnchoredEvent.InputTuple,
      SovereigntyAnchoredEvent.OutputTuple,
      SovereigntyAnchoredEvent.OutputObject
    >;

    "TerminalStatusChanged(uint8)": TypedContractEvent<
      TerminalStatusChangedEvent.InputTuple,
      TerminalStatusChangedEvent.OutputTuple,
      TerminalStatusChangedEvent.OutputObject
    >;
    TerminalStatusChanged: TypedContractEvent<
      TerminalStatusChangedEvent.InputTuple,
      TerminalStatusChangedEvent.OutputTuple,
      TerminalStatusChangedEvent.OutputObject
    >;
  };
}
