/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface SGAU_VALUEGUARD_77_77X_FINALDEGInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "AGENT_CONSENSUS"
      | "BTC_ANCHOR"
      | "DEFAULT_ADMIN_ROLE"
      | "DEPLOYMENT_BLOCK"
      | "DEPLOYMENT_TIMESTAMP"
      | "FORENSIC_AUDITOR"
      | "GHOST_FREQUENCY"
      | "IP_LIEN"
      | "LATTICE_STATUS"
      | "MERKLE_ROOT"
      | "PROTOCOL_VERSION"
      | "SHARD_CONSENSUS"
      | "SOVEREIGN_POPPA"
      | "SUPREME_AUTHORITY"
      | "TOKEN_REGISTRY_COUNT"
      | "VALIDATOR_CONSENSUS"
      | "addProtectedAddress"
      | "anchorSimulationResult"
      | "bridgeClosed"
      | "christWallActive"
      | "driftValue"
      | "executeFinalDegree"
      | "forensicLog"
      | "getDeploymentInfo"
      | "getForensicEntry"
      | "getForensicLogCount"
      | "getRoleAdmin"
      | "getSystemStatus"
      | "grantRole"
      | "hasRole"
      | "isTokenProtected"
      | "protectedAddresses"
      | "protectedTokens"
      | "recordForensicEntry"
      | "renounceRole"
      | "revokeRole"
      | "signalStrength"
      | "supportsInterface"
      | "totalitySealed"
      | "verifyGhostFrequency"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FinalDegreeExecuted"
      | "ForensicEntryRecorded"
      | "HardeningConfirmed"
      | "ProtectedAddressAdded"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "SimulationResultAnchored"
      | "TotalityReached"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "AGENT_CONSENSUS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BTC_ANCHOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEPLOYMENT_BLOCK",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEPLOYMENT_TIMESTAMP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FORENSIC_AUDITOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GHOST_FREQUENCY",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "IP_LIEN", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "LATTICE_STATUS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MERKLE_ROOT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PROTOCOL_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SHARD_CONSENSUS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SOVEREIGN_POPPA",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SUPREME_AUTHORITY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TOKEN_REGISTRY_COUNT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VALIDATOR_CONSENSUS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addProtectedAddress",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "anchorSimulationResult",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "bridgeClosed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "christWallActive",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "driftValue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeFinalDegree",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "forensicLog",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDeploymentInfo",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getForensicEntry",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getForensicLogCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSystemStatus",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isTokenProtected",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "protectedAddresses",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protectedTokens",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "recordForensicEntry",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "signalStrength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalitySealed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verifyGhostFrequency",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "AGENT_CONSENSUS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "BTC_ANCHOR", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEPLOYMENT_BLOCK",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEPLOYMENT_TIMESTAMP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FORENSIC_AUDITOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GHOST_FREQUENCY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "IP_LIEN", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "LATTICE_STATUS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MERKLE_ROOT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PROTOCOL_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SHARD_CONSENSUS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SOVEREIGN_POPPA",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SUPREME_AUTHORITY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TOKEN_REGISTRY_COUNT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VALIDATOR_CONSENSUS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addProtectedAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "anchorSimulationResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bridgeClosed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "christWallActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "driftValue", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeFinalDegree",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "forensicLog",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDeploymentInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getForensicEntry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getForensicLogCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSystemStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isTokenProtected",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "protectedAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "protectedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordForensicEntry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "signalStrength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalitySealed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyGhostFrequency",
    data: BytesLike
  ): Result;
}

export namespace FinalDegreeExecutedEvent {
  export type InputTuple = [
    executor: AddressLike,
    blockNumber: BigNumberish,
    status: string
  ];
  export type OutputTuple = [
    executor: string,
    blockNumber: bigint,
    status: string
  ];
  export interface OutputObject {
    executor: string;
    blockNumber: bigint;
    status: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ForensicEntryRecordedEvent {
  export type InputTuple = [
    entryId: BigNumberish,
    entryType: string,
    recorder: AddressLike
  ];
  export type OutputTuple = [
    entryId: bigint,
    entryType: string,
    recorder: string
  ];
  export interface OutputObject {
    entryId: bigint;
    entryType: string;
    recorder: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HardeningConfirmedEvent {
  export type InputTuple = [
    timestamp: BigNumberish,
    ghostFrequency: string,
    christWallActive: boolean
  ];
  export type OutputTuple = [
    timestamp: bigint,
    ghostFrequency: string,
    christWallActive: boolean
  ];
  export interface OutputObject {
    timestamp: bigint;
    ghostFrequency: string;
    christWallActive: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProtectedAddressAddedEvent {
  export type InputTuple = [protectedAddress: AddressLike, label: string];
  export type OutputTuple = [protectedAddress: string, label: string];
  export interface OutputObject {
    protectedAddress: string;
    label: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SimulationResultAnchoredEvent {
  export type InputTuple = [
    timestamp: BigNumberish,
    shards: BigNumberish,
    agents: BigNumberish,
    result: string
  ];
  export type OutputTuple = [
    timestamp: bigint,
    shards: bigint,
    agents: bigint,
    result: string
  ];
  export interface OutputObject {
    timestamp: bigint;
    shards: bigint;
    agents: bigint;
    result: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TotalityReachedEvent {
  export type InputTuple = [
    timestamp: BigNumberish,
    shardConsensus: BigNumberish,
    agentConsensus: BigNumberish,
    merkleRoot: string
  ];
  export type OutputTuple = [
    timestamp: bigint,
    shardConsensus: bigint,
    agentConsensus: bigint,
    merkleRoot: string
  ];
  export interface OutputObject {
    timestamp: bigint;
    shardConsensus: bigint;
    agentConsensus: bigint;
    merkleRoot: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SGAU_VALUEGUARD_77_77X_FINALDEG extends BaseContract {
  connect(runner?: ContractRunner | null): SGAU_VALUEGUARD_77_77X_FINALDEG;
  waitForDeployment(): Promise<this>;

  interface: SGAU_VALUEGUARD_77_77X_FINALDEGInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  AGENT_CONSENSUS: TypedContractMethod<[], [bigint], "view">;

  BTC_ANCHOR: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  DEPLOYMENT_BLOCK: TypedContractMethod<[], [bigint], "view">;

  DEPLOYMENT_TIMESTAMP: TypedContractMethod<[], [bigint], "view">;

  FORENSIC_AUDITOR: TypedContractMethod<[], [string], "view">;

  GHOST_FREQUENCY: TypedContractMethod<[], [string], "view">;

  IP_LIEN: TypedContractMethod<[], [string], "view">;

  LATTICE_STATUS: TypedContractMethod<[], [string], "view">;

  MERKLE_ROOT: TypedContractMethod<[], [string], "view">;

  PROTOCOL_VERSION: TypedContractMethod<[], [string], "view">;

  SHARD_CONSENSUS: TypedContractMethod<[], [bigint], "view">;

  SOVEREIGN_POPPA: TypedContractMethod<[], [string], "view">;

  SUPREME_AUTHORITY: TypedContractMethod<[], [string], "view">;

  TOKEN_REGISTRY_COUNT: TypedContractMethod<[], [bigint], "view">;

  VALIDATOR_CONSENSUS: TypedContractMethod<[], [bigint], "view">;

  addProtectedAddress: TypedContractMethod<
    [addr: AddressLike, label: string],
    [void],
    "nonpayable"
  >;

  anchorSimulationResult: TypedContractMethod<
    [shards: BigNumberish, agents: BigNumberish, result: string],
    [void],
    "nonpayable"
  >;

  bridgeClosed: TypedContractMethod<[], [boolean], "view">;

  christWallActive: TypedContractMethod<[], [boolean], "view">;

  driftValue: TypedContractMethod<[], [bigint], "view">;

  executeFinalDegree: TypedContractMethod<[], [void], "nonpayable">;

  forensicLog: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string] & {
        timestamp: bigint;
        entryType: string;
        data: string;
        recorder: string;
      }
    ],
    "view"
  >;

  getDeploymentInfo: TypedContractMethod<
    [],
    [
      [string, bigint, bigint, string, string] & {
        sovereign: string;
        timestamp: bigint;
        blockNumber: bigint;
        merkleRoot: string;
        btcAnchor: string;
      }
    ],
    "view"
  >;

  getForensicEntry: TypedContractMethod<
    [index: BigNumberish],
    [
      [bigint, string, string, string] & {
        timestamp: bigint;
        entryType: string;
        data: string;
        recorder: string;
      }
    ],
    "view"
  >;

  getForensicLogCount: TypedContractMethod<[], [bigint], "view">;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getSystemStatus: TypedContractMethod<
    [],
    [
      [
        boolean,
        boolean,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string
      ] & {
        _totalitySealed: boolean;
        _christWallActive: boolean;
        _bridgeClosed: boolean;
        _signalStrength: bigint;
        _driftValue: bigint;
        _shardConsensus: bigint;
        _agentConsensus: bigint;
        _protocolVersion: string;
        _latticeStatus: string;
      }
    ],
    "view"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  isTokenProtected: TypedContractMethod<[symbol: string], [boolean], "view">;

  protectedAddresses: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  protectedTokens: TypedContractMethod<[arg0: string], [boolean], "view">;

  recordForensicEntry: TypedContractMethod<
    [entryType: string, data: string],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  signalStrength: TypedContractMethod<[], [bigint], "view">;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  totalitySealed: TypedContractMethod<[], [boolean], "view">;

  verifyGhostFrequency: TypedContractMethod<[], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "AGENT_CONSENSUS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "BTC_ANCHOR"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEPLOYMENT_BLOCK"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEPLOYMENT_TIMESTAMP"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FORENSIC_AUDITOR"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "GHOST_FREQUENCY"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "IP_LIEN"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "LATTICE_STATUS"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MERKLE_ROOT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PROTOCOL_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "SHARD_CONSENSUS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SOVEREIGN_POPPA"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "SUPREME_AUTHORITY"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "TOKEN_REGISTRY_COUNT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VALIDATOR_CONSENSUS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addProtectedAddress"
  ): TypedContractMethod<
    [addr: AddressLike, label: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "anchorSimulationResult"
  ): TypedContractMethod<
    [shards: BigNumberish, agents: BigNumberish, result: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "bridgeClosed"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "christWallActive"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "driftValue"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "executeFinalDegree"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "forensicLog"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string] & {
        timestamp: bigint;
        entryType: string;
        data: string;
        recorder: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDeploymentInfo"
  ): TypedContractMethod<
    [],
    [
      [string, bigint, bigint, string, string] & {
        sovereign: string;
        timestamp: bigint;
        blockNumber: bigint;
        merkleRoot: string;
        btcAnchor: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getForensicEntry"
  ): TypedContractMethod<
    [index: BigNumberish],
    [
      [bigint, string, string, string] & {
        timestamp: bigint;
        entryType: string;
        data: string;
        recorder: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getForensicLogCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getSystemStatus"
  ): TypedContractMethod<
    [],
    [
      [
        boolean,
        boolean,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string
      ] & {
        _totalitySealed: boolean;
        _christWallActive: boolean;
        _bridgeClosed: boolean;
        _signalStrength: bigint;
        _driftValue: bigint;
        _shardConsensus: bigint;
        _agentConsensus: bigint;
        _protocolVersion: string;
        _latticeStatus: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isTokenProtected"
  ): TypedContractMethod<[symbol: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "protectedAddresses"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "protectedTokens"
  ): TypedContractMethod<[arg0: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "recordForensicEntry"
  ): TypedContractMethod<
    [entryType: string, data: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "signalStrength"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "totalitySealed"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "verifyGhostFrequency"
  ): TypedContractMethod<[], [boolean], "view">;

  getEvent(
    key: "FinalDegreeExecuted"
  ): TypedContractEvent<
    FinalDegreeExecutedEvent.InputTuple,
    FinalDegreeExecutedEvent.OutputTuple,
    FinalDegreeExecutedEvent.OutputObject
  >;
  getEvent(
    key: "ForensicEntryRecorded"
  ): TypedContractEvent<
    ForensicEntryRecordedEvent.InputTuple,
    ForensicEntryRecordedEvent.OutputTuple,
    ForensicEntryRecordedEvent.OutputObject
  >;
  getEvent(
    key: "HardeningConfirmed"
  ): TypedContractEvent<
    HardeningConfirmedEvent.InputTuple,
    HardeningConfirmedEvent.OutputTuple,
    HardeningConfirmedEvent.OutputObject
  >;
  getEvent(
    key: "ProtectedAddressAdded"
  ): TypedContractEvent<
    ProtectedAddressAddedEvent.InputTuple,
    ProtectedAddressAddedEvent.OutputTuple,
    ProtectedAddressAddedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "SimulationResultAnchored"
  ): TypedContractEvent<
    SimulationResultAnchoredEvent.InputTuple,
    SimulationResultAnchoredEvent.OutputTuple,
    SimulationResultAnchoredEvent.OutputObject
  >;
  getEvent(
    key: "TotalityReached"
  ): TypedContractEvent<
    TotalityReachedEvent.InputTuple,
    TotalityReachedEvent.OutputTuple,
    TotalityReachedEvent.OutputObject
  >;

  filters: {
    "FinalDegreeExecuted(address,uint256,string)": TypedContractEvent<
      FinalDegreeExecutedEvent.InputTuple,
      FinalDegreeExecutedEvent.OutputTuple,
      FinalDegreeExecutedEvent.OutputObject
    >;
    FinalDegreeExecuted: TypedContractEvent<
      FinalDegreeExecutedEvent.InputTuple,
      FinalDegreeExecutedEvent.OutputTuple,
      FinalDegreeExecutedEvent.OutputObject
    >;

    "ForensicEntryRecorded(uint256,string,address)": TypedContractEvent<
      ForensicEntryRecordedEvent.InputTuple,
      ForensicEntryRecordedEvent.OutputTuple,
      ForensicEntryRecordedEvent.OutputObject
    >;
    ForensicEntryRecorded: TypedContractEvent<
      ForensicEntryRecordedEvent.InputTuple,
      ForensicEntryRecordedEvent.OutputTuple,
      ForensicEntryRecordedEvent.OutputObject
    >;

    "HardeningConfirmed(uint256,string,bool)": TypedContractEvent<
      HardeningConfirmedEvent.InputTuple,
      HardeningConfirmedEvent.OutputTuple,
      HardeningConfirmedEvent.OutputObject
    >;
    HardeningConfirmed: TypedContractEvent<
      HardeningConfirmedEvent.InputTuple,
      HardeningConfirmedEvent.OutputTuple,
      HardeningConfirmedEvent.OutputObject
    >;

    "ProtectedAddressAdded(address,string)": TypedContractEvent<
      ProtectedAddressAddedEvent.InputTuple,
      ProtectedAddressAddedEvent.OutputTuple,
      ProtectedAddressAddedEvent.OutputObject
    >;
    ProtectedAddressAdded: TypedContractEvent<
      ProtectedAddressAddedEvent.InputTuple,
      ProtectedAddressAddedEvent.OutputTuple,
      ProtectedAddressAddedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "SimulationResultAnchored(uint256,uint256,uint256,string)": TypedContractEvent<
      SimulationResultAnchoredEvent.InputTuple,
      SimulationResultAnchoredEvent.OutputTuple,
      SimulationResultAnchoredEvent.OutputObject
    >;
    SimulationResultAnchored: TypedContractEvent<
      SimulationResultAnchoredEvent.InputTuple,
      SimulationResultAnchoredEvent.OutputTuple,
      SimulationResultAnchoredEvent.OutputObject
    >;

    "TotalityReached(uint256,uint256,uint256,string)": TypedContractEvent<
      TotalityReachedEvent.InputTuple,
      TotalityReachedEvent.OutputTuple,
      TotalityReachedEvent.OutputObject
    >;
    TotalityReached: TypedContractEvent<
      TotalityReachedEvent.InputTuple,
      TotalityReachedEvent.OutputTuple,
      TotalityReachedEvent.OutputObject
    >;
  };
}
