// Case CUD-26-682107 Document Index Data
// San Francisco Superior Court, Department 12
// Hon. Michelle Tong

export type DocStatus = 'FILED' | 'PENDING' | 'LODGED' | 'ACTIVE' | 'EXECUTED';
export type DocType = 'ANS' | 'DEC' | 'POS' | 'CM-010' | 'NOT' | 'MOT' | 'MPA' | 'ORD' | 'DEM' | 'RJN' | 'EXH' | 'COMP' | 'XCOMP' | 'IDX' | 'GTW' | 'FW-001' | 'ADA' | 'GRIEV';
export type Stack = 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' | 'H' | 'EXT' | 'I' | 'J';

export interface CaseDocument {
  docNumber: string;
  title: string;
  shortDescription: string;
  type: DocType;
  stack: Stack;
  status: DocStatus;
  filingDate: string;
  clerkNote?: string;
  relatedDocs?: string[];
  priority?: 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW';
}

export const CASE_INFO = {
  caseNumber: 'CUD-26-682107',
  relatedCase: 'CCH-28-589086',
  court: 'Superior Court of California, County of San Francisco',
  department: '12',
  judge: 'Hon. Michelle Tong',
  plaintiff: 'Swords to Plowshares, a California Nonprofit Corporation',
  defendant: 'Donald Ernest Gillson, aka Donny Gillson',
  defendantStatus: 'In Pro Per',
  masterRepository: 'https://drive.google.com/drive/folders/1x9DGaev6hrRLngAx2plNBOoxrJzGw3f8',
  filingDate: 'May 24, 2026',
};

export const STACK_DESCRIPTIONS: Record<Stack, { name: string; description: string; docCount: number }> = {
  'A': { name: 'Answer & Initial Pleadings', description: 'Initial response filings and case management documents', docCount: 5 },
  'B': { name: 'Ex Parte Stay', description: 'Emergency stay motions and supporting declarations', docCount: 5 },
  'C': { name: 'Demurrer', description: 'Demurrer to complaint and points & authorities', docCount: 5 },
  'D': { name: 'Motion to Strike', description: 'Motion to strike portions of complaint', docCount: 5 },
  'E': { name: 'ADA, Habitability & Contextual', description: 'Accommodation requests, habitability issues, and contextual declarations', docCount: 7 },
  'F': { name: 'Motion to Quash & Service Defects', description: 'Jurisdiction challenges and service of process issues', docCount: 7 },
  'G': { name: 'Complaints & Cross-Complaint', description: 'Regulatory complaints and cross-complaint filings', docCount: 4 },
  'H': { name: 'Evidence Index & Motions', description: 'Evidence cataloging, retaliation motions, and fraud allegations', docCount: 5 },
  'EXT': { name: 'Extended Notices', description: 'Extended notices and master bundle filings', docCount: 3 },
  'I': { name: 'Regulatory & Environmental Exhibits', description: 'Regulatory compliance and environmental hazard exhibits', docCount: 5 },
  'J': { name: 'Forensic Dossier & Current Campaign', description: 'Forensic analysis, fee waiver, ADA requests, and current filings', docCount: 21 },
};

export const DOC_TYPE_LABELS: Record<DocType, string> = {
  'ANS': 'Answer',
  'DEC': 'Declaration',
  'POS': 'Proof of Service',
  'CM-010': 'Case Cover Sheet',
  'NOT': 'Notice',
  'MOT': 'Motion',
  'MPA': 'Memorandum P&A',
  'ORD': 'Proposed Order',
  'DEM': 'Demurrer',
  'RJN': 'Request for Judicial Notice',
  'EXH': 'Exhibit',
  'COMP': 'Complaint',
  'XCOMP': 'Cross-Complaint',
  'IDX': 'Index',
  'GTW': 'Gateway Document',
  'FW-001': 'Fee Waiver Application',
  'ADA': 'ADA Accommodation Request',
  'GRIEV': 'Grievance',
};

export const CASE_DOCUMENTS: CaseDocument[] = [
  // PRIORITY REVIEW SEQUENCE
  {
    docNumber: '000-AA0-R1',
    title: 'Lead Clerk Filing Statement and Master Repository Roadmap',
    shortDescription: 'Primary index paper providing no-repeat roadmap and superseding repository link',
    type: 'IDX',
    stack: 'A',
    status: 'FILED',
    filingDate: '2026-05-24',
    clerkNote: 'Open first. Provides the no-repeat roadmap and superseding repository link.',
    priority: 'CRITICAL',
  },
  {
    docNumber: '092',
    title: 'Electronic MC-410 Accommodation Request',
    shortDescription: 'Operative accommodation filing requesting ADA / Rule 1.100 processing and e-filing access treatment',
    type: 'ADA',
    stack: 'J',
    status: 'PENDING',
    filingDate: '2026-05-20',
    clerkNote: 'Operative accommodation filing; requests ADA / Rule 1.100 processing and e-filing access treatment.',
    priority: 'CRITICAL',
  },
  {
    docNumber: '094-R1/R2',
    title: 'Combined Electronic Submission / Distribution Notice',
    shortDescription: 'Expanded routing, ADA coordinator notice, and written-response request',
    type: 'NOT',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-20',
    clerkNote: 'Provides expanded routing, ADA coordinator notice, and written-response request.',
    priority: 'CRITICAL',
  },
  {
    docNumber: '072',
    title: 'Master Gateway Index',
    shortDescription: 'Gateway orientation for ADA accommodation, e-filing compliance, and full defense record',
    type: 'GTW',
    stack: 'J',
    status: 'EXECUTED',
    filingDate: '2026-05-19',
    clerkNote: 'Gateway filing for ADA accommodation, e-filing compliance, and full 72-document defense record orientation.',
    priority: 'CRITICAL',
  },
  
  // STACK A — ANSWER & INITIAL PLEADINGS
  {
    docNumber: '01',
    title: 'Answer to Unlawful Detainer Complaint',
    shortDescription: 'Defendant\'s answer to the complaint with affirmative defenses',
    type: 'ANS',
    stack: 'A',
    status: 'FILED',
    filingDate: '2026-04-15',
  },
  {
    docNumber: '02',
    title: 'Declaration of Donald Ernest Gillson',
    shortDescription: 'Defendant declaration authenticating factual background, service defects, federal-enclave issue, ADA needs, and exhibit record',
    type: 'DEC',
    stack: 'A',
    status: 'FILED',
    filingDate: '2026-04-15',
  },
  {
    docNumber: '03',
    title: 'Proof of Service - Answer',
    shortDescription: 'Proof of service for answer filing',
    type: 'POS',
    stack: 'A',
    status: 'FILED',
    filingDate: '2026-04-15',
  },
  {
    docNumber: '04',
    title: 'Civil Case Cover Sheet',
    shortDescription: 'CM-010 case cover sheet for civil matter',
    type: 'CM-010',
    stack: 'A',
    status: 'FILED',
    filingDate: '2026-04-15',
  },
  {
    docNumber: '05',
    title: 'Civil Cross-Complaint',
    shortDescription: 'Cross-Complaint asserting retaliation, civil-rights violations, elder/dependent-adult abuse, witness interference, fraud, and related claims',
    type: 'XCOMP',
    stack: 'A',
    status: 'FILED',
    filingDate: '2026-04-18',
    priority: 'HIGH',
  },
  
  // STACK B — EX PARTE STAY
  {
    docNumber: '06',
    title: 'Ex Parte Motion for Stay',
    shortDescription: 'Emergency motion to stay unlawful detainer proceedings',
    type: 'MOT',
    stack: 'B',
    status: 'FILED',
    filingDate: '2026-04-16',
  },
  {
    docNumber: '07',
    title: 'Declaration in Support of Stay',
    shortDescription: 'Supporting declaration for ex parte stay motion',
    type: 'DEC',
    stack: 'B',
    status: 'FILED',
    filingDate: '2026-04-16',
  },
  {
    docNumber: '08',
    title: 'Proposed Order - Stay',
    shortDescription: 'Proposed order granting stay of proceedings',
    type: 'ORD',
    stack: 'B',
    status: 'FILED',
    filingDate: '2026-04-16',
  },
  {
    docNumber: '09',
    title: 'Notice of Related Case',
    shortDescription: 'Notice identifying relationship to CCH-28-589086',
    type: 'NOT',
    stack: 'B',
    status: 'FILED',
    filingDate: '2026-04-16',
  },
  {
    docNumber: '10',
    title: 'Memorandum of Points & Authorities - Stay',
    shortDescription: 'Legal memorandum supporting ex parte stay',
    type: 'MPA',
    stack: 'B',
    status: 'FILED',
    filingDate: '2026-04-16',
  },
  
  // STACK C — DEMURRER
  {
    docNumber: '11',
    title: 'Demurrer to Complaint',
    shortDescription: 'Demurrer challenging legal sufficiency of complaint',
    type: 'DEM',
    stack: 'C',
    status: 'FILED',
    filingDate: '2026-04-18',
  },
  {
    docNumber: '12',
    title: 'Notice of Demurrer',
    shortDescription: 'Notice of hearing on demurrer',
    type: 'NOT',
    stack: 'C',
    status: 'FILED',
    filingDate: '2026-04-18',
  },
  {
    docNumber: '13',
    title: 'Points & Authorities - Demurrer',
    shortDescription: 'Legal memorandum supporting demurrer',
    type: 'MPA',
    stack: 'C',
    status: 'FILED',
    filingDate: '2026-04-18',
  },
  {
    docNumber: '14',
    title: 'Meet and Confer Declaration',
    shortDescription: 'Declaration regarding meet and confer efforts',
    type: 'DEC',
    stack: 'C',
    status: 'FILED',
    filingDate: '2026-04-18',
  },
  {
    docNumber: '15',
    title: 'Proposed Order - Demurrer',
    shortDescription: 'Proposed order sustaining demurrer',
    type: 'ORD',
    stack: 'C',
    status: 'FILED',
    filingDate: '2026-04-18',
  },
  
  // STACK D — MOTION TO STRIKE
  {
    docNumber: '16',
    title: 'Motion to Strike',
    shortDescription: 'Motion to strike portions of complaint',
    type: 'MOT',
    stack: 'D',
    status: 'FILED',
    filingDate: '2026-04-20',
  },
  {
    docNumber: '17',
    title: 'Motion for Sanctions / Fee Disgorgement',
    shortDescription: 'Motion seeking sanctions, attorney-fee disgorgement, civil penalty documentation, and potential referral',
    type: 'MOT',
    stack: 'D',
    status: 'FILED',
    filingDate: '2026-04-20',
    priority: 'HIGH',
  },
  {
    docNumber: '18',
    title: 'Points & Authorities - Strike',
    shortDescription: 'Legal memorandum supporting motion to strike',
    type: 'MPA',
    stack: 'D',
    status: 'FILED',
    filingDate: '2026-04-20',
  },
  {
    docNumber: '19',
    title: 'Proposed Order - Strike',
    shortDescription: 'Proposed order granting motion to strike',
    type: 'ORD',
    stack: 'D',
    status: 'FILED',
    filingDate: '2026-04-20',
  },
  {
    docNumber: '20',
    title: 'Pre-Hearing Procedural Briefing Notice',
    shortDescription: 'Threshold briefing identifying jurisdiction, notice, retaliation, ADA, and agency-review issues',
    type: 'NOT',
    stack: 'D',
    status: 'FILED',
    filingDate: '2026-04-20',
  },
  
  // STACK E — ADA, HABITABILITY & CONTEXTUAL
  {
    docNumber: '21',
    title: 'Declaration and Exhibit Packet',
    shortDescription: 'Defendant declaration authenticating factual background, service defects, federal-enclave issue, ADA needs, and exhibit record',
    type: 'DEC',
    stack: 'E',
    status: 'FILED',
    filingDate: '2026-04-22',
    priority: 'HIGH',
  },
  {
    docNumber: '22',
    title: 'Clinical Verification Declaration',
    shortDescription: 'Medical verification supporting ADA accommodation requests',
    type: 'DEC',
    stack: 'E',
    status: 'FILED',
    filingDate: '2026-04-22',
  },
  {
    docNumber: '23',
    title: 'SMTP 550 Blockade Notice',
    shortDescription: 'Supplemental forensic notice documenting email rejection events and requesting protection',
    type: 'NOT',
    stack: 'E',
    status: 'FILED',
    filingDate: '2026-04-22',
  },
  {
    docNumber: '24',
    title: 'Maintenance Demand Declaration',
    shortDescription: 'Declaration documenting habitability maintenance demands',
    type: 'DEC',
    stack: 'E',
    status: 'FILED',
    filingDate: '2026-04-22',
  },
  {
    docNumber: '25',
    title: 'Inpatient Timeline Declaration',
    shortDescription: 'Declaration establishing timeline of medical treatment',
    type: 'DEC',
    stack: 'E',
    status: 'FILED',
    filingDate: '2026-04-22',
  },
  {
    docNumber: '26',
    title: 'Video Evidence / Habitability Notice',
    shortDescription: 'Notice preserving Exhibit G video evidence regarding habitability conditions, infestation, chemical exposure',
    type: 'NOT',
    stack: 'E',
    status: 'FILED',
    filingDate: '2026-04-22',
  },
  {
    docNumber: '26-B',
    title: 'Forensic Medical / Chemical Injury Analysis',
    shortDescription: 'Supplemental forensic analysis of chemical injury, medical impact, and Exhibit G transmittal',
    type: 'DEC',
    stack: 'E',
    status: 'FILED',
    filingDate: '2026-04-23',
  },
  {
    docNumber: '27',
    title: 'ADA Interactive Process Declaration',
    shortDescription: 'Declaration documenting actual knowledge of accommodation requests and unilateral termination of ADA/FEHA interactive process',
    type: 'DEC',
    stack: 'E',
    status: 'FILED',
    filingDate: '2026-04-23',
    priority: 'HIGH',
  },
  
  // STACK F — MOTION TO QUASH & SERVICE DEFECTS
  {
    docNumber: '28',
    title: 'Motion to Quash Service of Summons',
    shortDescription: 'Motion challenging service and jurisdiction, including federal-enclave and personal-jurisdiction arguments',
    type: 'MOT',
    stack: 'F',
    status: 'FILED',
    filingDate: '2026-04-25',
    priority: 'CRITICAL',
  },
  {
    docNumber: '29-R2',
    title: 'Reissued Declaration re Kolby Losik',
    shortDescription: 'Reissued declaration concerning witness intimidation, unauthorized disclosure, supportive-services conduct',
    type: 'DEC',
    stack: 'F',
    status: 'FILED',
    filingDate: '2026-04-25',
    priority: 'HIGH',
  },
  {
    docNumber: '30',
    title: 'Request for Judicial Notice - Federal',
    shortDescription: 'Request for judicial notice of federal jurisdiction issues',
    type: 'RJN',
    stack: 'F',
    status: 'FILED',
    filingDate: '2026-04-25',
  },
  {
    docNumber: '31',
    title: 'Points & Authorities - Quash',
    shortDescription: 'Legal memorandum supporting motion to quash',
    type: 'MPA',
    stack: 'F',
    status: 'FILED',
    filingDate: '2026-04-25',
  },
  {
    docNumber: '32',
    title: 'Exhibit G Video Transmittal',
    shortDescription: 'Exhibit cover sheet for video evidence transmittal',
    type: 'EXH',
    stack: 'F',
    status: 'FILED',
    filingDate: '2026-04-25',
  },
  {
    docNumber: '33',
    title: 'Service Defect Declaration',
    shortDescription: 'Declaration documenting defects in service of process',
    type: 'DEC',
    stack: 'F',
    status: 'FILED',
    filingDate: '2026-04-25',
  },
  {
    docNumber: '34',
    title: 'Proof of Service - Firewall',
    shortDescription: 'Proof of service documenting communication barriers',
    type: 'POS',
    stack: 'F',
    status: 'FILED',
    filingDate: '2026-04-25',
  },
  
  // STACK G — COMPLAINTS & CROSS-COMPLAINT
  {
    docNumber: '35',
    title: 'DRE Complaint',
    shortDescription: 'Complaint filed with Department of Real Estate',
    type: 'COMP',
    stack: 'G',
    status: 'FILED',
    filingDate: '2026-04-28',
  },
  {
    docNumber: '36',
    title: 'BBS Complaint',
    shortDescription: 'Complaint filed with Board of Behavioral Sciences',
    type: 'DEC',
    stack: 'G',
    status: 'FILED',
    filingDate: '2026-04-28',
  },
  {
    docNumber: '37',
    title: 'Cross-Complaint',
    shortDescription: 'Cross-complaint against plaintiff and related parties',
    type: 'XCOMP',
    stack: 'G',
    status: 'FILED',
    filingDate: '2026-04-28',
  },
  {
    docNumber: '38',
    title: 'Notice of Lodging',
    shortDescription: 'Notice of lodging for cross-complaint materials',
    type: 'NOT',
    stack: 'G',
    status: 'FILED',
    filingDate: '2026-04-28',
  },
  
  // STACK H — EVIDENCE INDEX & MOTIONS
  {
    docNumber: '39',
    title: 'Evidence Index',
    shortDescription: 'Master index of all evidence filed in the case',
    type: 'IDX',
    stack: 'H',
    status: 'FILED',
    filingDate: '2026-05-01',
  },
  {
    docNumber: '40',
    title: 'Motion - Statutory Presumption Retaliation',
    shortDescription: 'Motion establishing statutory presumption of retaliation',
    type: 'MOT',
    stack: 'H',
    status: 'FILED',
    filingDate: '2026-05-01',
    priority: 'HIGH',
  },
  {
    docNumber: '41',
    title: 'Supplemental Facts Declaration',
    shortDescription: 'Declaration providing supplemental facts for motions',
    type: 'DEC',
    stack: 'H',
    status: 'FILED',
    filingDate: '2026-05-01',
  },
  {
    docNumber: '42',
    title: 'Motion to Dismiss - Fraud on Court and Void Notice',
    shortDescription: 'Motion seeking dismissal based on void 3-day notice, fraud on the court, unlicensed property-management issue, and sanctions',
    type: 'MOT',
    stack: 'H',
    status: 'FILED',
    filingDate: '2026-05-01',
    priority: 'CRITICAL',
  },
  {
    docNumber: '43',
    title: 'Notice of Master Evidence Depository',
    shortDescription: 'Notice establishing master evidence repository location',
    type: 'NOT',
    stack: 'H',
    status: 'FILED',
    filingDate: '2026-05-01',
  },
  
  // STACK EXT — EXTENDED NOTICES
  {
    docNumber: '44',
    title: 'Notice of Service Failure',
    shortDescription: 'Notice documenting service delivery failures',
    type: 'NOT',
    stack: 'EXT',
    status: 'FILED',
    filingDate: '2026-05-03',
  },
  {
    docNumber: '45',
    title: 'Notice of Filing and Lodging',
    shortDescription: 'Notice of filing for extended materials',
    type: 'NOT',
    stack: 'EXT',
    status: 'LODGED',
    filingDate: '2026-05-03',
    clerkNote: 'LODGED — PENDING DOCKET',
  },
  {
    docNumber: '46',
    title: 'Master Bundle v5',
    shortDescription: 'Consolidated master bundle proof of service',
    type: 'POS',
    stack: 'EXT',
    status: 'LODGED',
    filingDate: '2026-05-03',
    clerkNote: 'LODGED — PENDING DOCKET',
  },
  
  // STACK I — EXHIBITS (Regulatory & Environmental)
  {
    docNumber: '47',
    title: 'Exhibit A-48-1: Regulatory Non-Compliance',
    shortDescription: 'Exhibit documenting regulatory non-compliance issues',
    type: 'EXH',
    stack: 'I',
    status: 'LODGED',
    filingDate: '2026-05-05',
    clerkNote: 'LODGED — PENDING DIRECTORY',
  },
  {
    docNumber: '48',
    title: 'Exhibit A-48-2: Environmental Hazard',
    shortDescription: 'Exhibit documenting environmental hazard conditions',
    type: 'EXH',
    stack: 'I',
    status: 'LODGED',
    filingDate: '2026-05-05',
    clerkNote: 'LODGED — PENDING DIRECTORY',
  },
  {
    docNumber: '49',
    title: 'Exhibit A-48-3: Infestation Density',
    shortDescription: 'Exhibit documenting pest infestation conditions',
    type: 'EXH',
    stack: 'I',
    status: 'LODGED',
    filingDate: '2026-05-05',
    clerkNote: 'LODGED — PENDING DIRECTORY',
  },
  {
    docNumber: '50',
    title: 'Exhibit A-48-4: Investigative Data Stromberg',
    shortDescription: 'Exhibit containing investigative data and analysis',
    type: 'EXH',
    stack: 'I',
    status: 'LODGED',
    filingDate: '2026-05-05',
    clerkNote: 'LODGED — PENDING DIRECTORY',
  },
  {
    docNumber: '51',
    title: 'Exhibit A-48-5: Medical Coordination',
    shortDescription: 'Exhibit documenting medical coordination issues',
    type: 'EXH',
    stack: 'I',
    status: 'LODGED',
    filingDate: '2026-05-05',
    clerkNote: 'LODGED — PENDING DIRECTORY',
  },
  
  // STACK J — FORENSIC DOSSIER & CURRENT CAMPAIGN
  {
    docNumber: '50',
    title: 'ADA Accommodation Compliance Notice',
    shortDescription: 'ADA notice requesting written acknowledgment, accessible filing methods, remote appearance, fee accommodation',
    type: 'ADA',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-06',
  },
  {
    docNumber: '56',
    title: 'Consolidated Forensic Dossier',
    shortDescription: 'Master forensic analysis and evidence compilation',
    type: 'DEC',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-08',
    priority: 'HIGH',
  },
  {
    docNumber: '57',
    title: 'Fee Waiver Application (FW-001)',
    shortDescription: 'Fee-waiver application based on public-benefit status, financial hardship, and access-to-court concerns',
    type: 'FW-001',
    stack: 'J',
    status: 'PENDING',
    filingDate: '2026-05-08',
    clerkNote: 'PENDING JUDICIAL RULING',
    priority: 'HIGH',
  },
  {
    docNumber: '58',
    title: 'ADA Accommodation Request',
    shortDescription: 'Formal ADA accommodation request under Rule 1.100',
    type: 'ADA',
    stack: 'J',
    status: 'PENDING',
    filingDate: '2026-05-08',
    clerkNote: 'PENDING JUDICIAL RULING',
  },
  {
    docNumber: '59',
    title: 'Notice of Lodging and Transmittal of Documents 56-58',
    shortDescription: 'Notice of lodging for documents 56 through 58',
    type: 'NOT',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-10',
  },
  {
    docNumber: '60',
    title: 'Administrative Contradiction and Continued Tenancy Notice',
    shortDescription: 'Notice arguing inspection scheduling and administrative treatment contradict unlawful-detainer posture',
    type: 'NOT',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-10',
    priority: 'HIGH',
  },
  {
    docNumber: '61',
    title: 'Supplemental Declaration - Misnaming Retaliation',
    shortDescription: 'Declaration documenting misnaming and retaliation patterns',
    type: 'DEC',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-10',
  },
  {
    docNumber: '62',
    title: 'Motion to Reconsider TRO - EDAA',
    shortDescription: 'Motion to reconsider temporary restraining order under Elder/Dependent Adult Abuse Act',
    type: 'MOT',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-12',
  },
  {
    docNumber: '63',
    title: 'Internal Grievance - Admin Exhaustion STP',
    shortDescription: 'Internal grievance for administrative exhaustion with Swords to Plowshares',
    type: 'GRIEV',
    stack: 'J',
    status: 'ACTIVE',
    filingDate: '2026-05-12',
    clerkNote: 'ACTIVE — 10-DAY CLOCK RUNNING',
  },
  {
    docNumber: '64',
    title: 'Bad Faith Litigation Conduct Statement',
    shortDescription: 'Statement preserving bad-faith litigation conduct for sanctions under procedural and retaliation theories',
    type: 'MOT',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-12',
  },
  {
    docNumber: '65',
    title: 'Denial of Reasonable Accommodations Chronological Record',
    shortDescription: 'Chronological record of ADA/FHA accommodation denials and failures to engage in interactive process',
    type: 'DEC',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-14',
    priority: 'HIGH',
  },
  {
    docNumber: '66',
    title: 'Constructive Eviction Chronological Record',
    shortDescription: 'Chronological record supporting constructive-eviction theory based on habitability, retaliation, and interference',
    type: 'DEC',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-14',
    priority: 'HIGH',
  },
  {
    docNumber: '67',
    title: 'Notice of Document Fraud - Backdated Notice to Quit',
    shortDescription: 'Notice alleging backdated or falsified notice to quit documents',
    type: 'NOT',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-14',
  },
  {
    docNumber: '68',
    title: 'Omnibus Transmittal - Mimecast Log - Notice of Lodgment',
    shortDescription: 'Omnibus notice including Mimecast forensic log and lodgment notice',
    type: 'NOT',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-15',
  },
  {
    docNumber: '69',
    title: 'Clerk-Direct Hard Block Notice',
    shortDescription: 'Notice of systemic e-filing hard block, request for manual lodgment, and ADA coordinator review',
    type: 'NOT',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-15',
  },
  {
    docNumber: '70',
    title: 'Falsified Documents - Retaliatory Campaign - Landrum',
    shortDescription: 'Declaration alleging falsified documents, false attestations, public posting of private tenant information',
    type: 'DEC',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-16',
  },
  {
    docNumber: '71',
    title: 'Master Index Cover Sheet Finalized',
    shortDescription: 'Finalized cover sheet for master document index',
    type: 'IDX',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-18',
  },
  {
    docNumber: '074',
    title: 'Related Case / Cross-Lodgment Notice',
    shortDescription: 'Notice identifying relationship between UD case and elder/dependent-adult abuse restraining-order matter',
    type: 'NOT',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-18',
  },
  {
    docNumber: '075',
    title: 'Judge Tong Related-Case Notice',
    shortDescription: 'Supplemental update regarding post-hearing retaliation and relationship between RO and UD records',
    type: 'NOT',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-18',
  },
  {
    docNumber: '079',
    title: 'IP Theft / ESI Preservation Notice',
    shortDescription: 'Notice adding trade-secret/IP theft theory and requesting ESI preservation regarding VALORAIPLUS',
    type: 'NOT',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-19',
  },
  {
    docNumber: '080',
    title: 'Omnibus Final Filing',
    shortDescription: 'Master closing filing consolidating all asserted causes of action and requested relief',
    type: 'MOT',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-20',
    priority: 'HIGH',
  },
  {
    docNumber: '081',
    title: 'Motion to Consolidate',
    shortDescription: 'Motion to consolidate related CUD and CCH proceedings based on common parties, facts, witnesses',
    type: 'MOT',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-20',
  },
  {
    docNumber: '082',
    title: 'Non-Party Stakeholder Notice',
    shortDescription: 'Notice of service to non-party stakeholders and request for docket entry',
    type: 'NOT',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-20',
  },
  {
    docNumber: '083',
    title: 'Cross-Lodgment Notice',
    shortDescription: 'Notice confirming cross-lodgment of consolidation motion into related CCH case',
    type: 'NOT',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-20',
  },
  {
    docNumber: '084',
    title: 'Corporate Malfeasance Notice',
    shortDescription: 'Notice alleging corporate malfeasance, bad-faith litigation conduct, and grounds for OSC or dismissal',
    type: 'NOT',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-21',
  },
  {
    docNumber: '087',
    title: 'Federal Grant Misuse Notice',
    shortDescription: 'Notice alleging misuse of federal housing/veteran-support funding under ADA/FHA/Section 504 theories',
    type: 'NOT',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-21',
    priority: 'HIGH',
  },
  {
    docNumber: '089-R2',
    title: 'Amended Motion to Compel Financial Disclosure Retainer',
    shortDescription: 'Motion to compel financial disclosure regarding retainer agreements',
    type: 'MOT',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-22',
  },
  {
    docNumber: '090-R2',
    title: 'Filing / POS Addendum',
    shortDescription: 'Corrected filing and proof-of-service addendum identifying additional index materials',
    type: 'POS',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-22',
  },
  {
    docNumber: '091-R2',
    title: 'Willful Regulatory Non-Compliance Notice',
    shortDescription: 'Notice alleging willful non-compliance after repeated opportunities to cure',
    type: 'NOT',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-22',
  },
  {
    docNumber: '096',
    title: 'Statement of Facts',
    shortDescription: 'Core statement supporting affirmative defenses, accommodation record, jurisdictional challenge',
    type: 'DEC',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-23',
    priority: 'HIGH',
  },
  {
    docNumber: '099-R1',
    title: 'Amended Request for Judicial Notice - Court Readability Index',
    shortDescription: 'Request for judicial notice regarding court readability and accessibility standards',
    type: 'RJN',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-23',
  },
  {
    docNumber: '102',
    title: 'Priority Tranche / Preservation Record',
    shortDescription: 'Amendment confirming priority filing tranche, preservation of staged materials, and non-abandonment',
    type: 'NOT',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-24',
  },
  {
    docNumber: '102-R2',
    title: 'Targeted Veterans / VTU Retaliation Notice',
    shortDescription: 'Notice identifying Jeff Wright, Jerry Bartlett, Dan Lucian as affected witnesses or targeted veteran tenants',
    type: 'NOT',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-24',
    priority: 'HIGH',
  },
  {
    docNumber: '103-R1',
    title: 'Courtesy Transmission / Witness Preservation Notice',
    shortDescription: 'Notice preserving text-message courtesy transmissions, witness identification, related-tenant contacts',
    type: 'NOT',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-24',
  },
  {
    docNumber: '106',
    title: 'FBI San Francisco Notice',
    shortDescription: 'Agency-intake and evidence-preservation notice regarding court-access obstruction, ADA/housing retaliation',
    type: 'NOT',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-24',
    priority: 'CRITICAL',
  },
];

// Utility functions
export function getDocumentsByStack(stack: Stack): CaseDocument[] {
  return CASE_DOCUMENTS.filter(doc => doc.stack === stack);
}

export function getDocumentsByStatus(status: DocStatus): CaseDocument[] {
  return CASE_DOCUMENTS.filter(doc => doc.status === status);
}

export function getDocumentsByType(type: DocType): CaseDocument[] {
  return CASE_DOCUMENTS.filter(doc => doc.type === type);
}

export function getPriorityDocuments(): CaseDocument[] {
  return CASE_DOCUMENTS.filter(doc => doc.priority === 'CRITICAL' || doc.priority === 'HIGH');
}

export function searchDocuments(query: string): CaseDocument[] {
  const lowerQuery = query.toLowerCase();
  return CASE_DOCUMENTS.filter(doc => 
    doc.title.toLowerCase().includes(lowerQuery) ||
    doc.shortDescription.toLowerCase().includes(lowerQuery) ||
    doc.docNumber.toLowerCase().includes(lowerQuery) ||
    doc.type.toLowerCase().includes(lowerQuery)
  );
}

export function getRecordSummary() {
  const total = CASE_DOCUMENTS.length;
  const filed = CASE_DOCUMENTS.filter(d => d.status === 'FILED').length;
  const pending = CASE_DOCUMENTS.filter(d => d.status === 'PENDING').length;
  const lodged = CASE_DOCUMENTS.filter(d => d.status === 'LODGED').length;
  const active = CASE_DOCUMENTS.filter(d => d.status === 'ACTIVE').length;
  const executed = CASE_DOCUMENTS.filter(d => d.status === 'EXECUTED').length;
  
  return { total, filed, pending, lodged, active, executed };
}
