// Case CUD-26-682107 Document Index Data
// San Francisco Superior Court, Department 12
// Hon. Michelle Tong

export type DocStatus = 'FILED' | 'PENDING' | 'LODGED' | 'ACTIVE' | 'EXECUTED';
export type DocType = 'ANS' | 'DEC' | 'POS' | 'CM-010' | 'NOT' | 'MOT' | 'MPA' | 'ORD' | 'DEM' | 'RJN' | 'EXH' | 'COMP' | 'XCOMP' | 'IDX' | 'GTW' | 'FW-001' | 'ADA' | 'GRIEV';
export type Stack = 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' | 'H' | 'EXT' | 'I' | 'J';

export interface CaseDocument {
  docNumber: string;
  title: string;
  shortDescription: string;
  type: DocType;
  stack: Stack;
  status: DocStatus;
  filingDate: string;
  clerkNote?: string;
  relatedDocs?: string[];
  priority?: 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW';
}

export const CASE_INFO = {
  caseNumber: 'CUD-26-682107',
  relatedCase: 'CCH-28-589086',
  court: 'Superior Court of California, County of San Francisco',
  department: '12',
  judge: 'Hon. Michelle Tong',
  plaintiff: 'Swords to Plowshares, a California Nonprofit Corporation',
  defendant: 'Donald Ernest Gillson, aka Donny Gillson',
  defendantStatus: 'In Pro Per',
  masterRepository: 'https://drive.google.com/drive/folders/1x9DGaev6hrRLngAx2plNBOoxrJzGw3f8',
  filingDate: 'May 24, 2026',
};

export const STACK_DESCRIPTIONS: Record<Stack, { name: string; description: string; docCount: number }> = {
  'A': { name: 'Answer & Initial Pleadings', description: 'Initial response filings and case management documents', docCount: 5 },
  'B': { name: 'Ex Parte Stay', description: 'Emergency stay motions and supporting declarations', docCount: 5 },
  'C': { name: 'Demurrer', description: 'Demurrer to complaint and points & authorities', docCount: 5 },
  'D': { name: 'Threshold Motions', description: 'Motion to strike, strategic legal memo (Dred Scott / Rickover parallels), sanctions motion, pre-hearing briefing, motion to quash', docCount: 6 },
  'E': { name: 'ADA, Habitability & Contextual', description: 'Accommodation requests, habitability issues, and contextual declarations', docCount: 7 },
  'F': { name: 'Motion to Quash & Service Defects', description: 'Jurisdiction challenges and service of process issues', docCount: 7 },
  'G': { name: 'Complaints & Cross-Complaint', description: 'Regulatory complaints and cross-complaint filings', docCount: 4 },
  'H': { name: 'Evidence Index & Motions', description: 'Evidence cataloging, retaliation motions, and fraud allegations', docCount: 5 },
  'EXT': { name: 'Extended Notices', description: 'Extended notices and master bundle filings', docCount: 3 },
  'I': { name: 'Regulatory & Environmental Exhibits', description: 'Regulatory compliance and environmental hazard exhibits', docCount: 5 },
  'J': { name: 'Forensic Dossier & Current Campaign', description: 'Forensic analysis, fee waiver, ADA requests, RO cross-reference, node map, and current filings', docCount: 24 },
};

export const DOC_TYPE_LABELS: Record<DocType, string> = {
  'ANS': 'Answer',
  'DEC': 'Declaration',
  'POS': 'Proof of Service',
  'CM-010': 'Case Cover Sheet',
  'NOT': 'Notice',
  'MOT': 'Motion',
  'MPA': 'Memorandum P&A',
  'ORD': 'Proposed Order',
  'DEM': 'Demurrer',
  'RJN': 'Request for Judicial Notice',
  'EXH': 'Exhibit',
  'COMP': 'Complaint',
  'XCOMP': 'Cross-Complaint',
  'IDX': 'Index',
  'GTW': 'Gateway Document',
  'FW-001': 'Fee Waiver Application',
  'ADA': 'ADA Accommodation Request',
  'GRIEV': 'Grievance',
};

export const CASE_DOCUMENTS: CaseDocument[] = [
  // PRIORITY REVIEW SEQUENCE
  {
    docNumber: '000-AA0-R1',
    title: 'Lead Clerk Filing Statement and Master Repository Roadmap',
    shortDescription: 'Primary index paper providing no-repeat roadmap and superseding repository link',
    type: 'IDX',
    stack: 'A',
    status: 'FILED',
    filingDate: '2026-05-24',
    clerkNote: 'Open first. Provides the no-repeat roadmap and superseding repository link.',
    priority: 'CRITICAL',
  },
  {
    docNumber: '092',
    title: 'Electronic MC-410 Accommodation Request',
    shortDescription: 'Operative accommodation filing requesting ADA / Rule 1.100 processing and e-filing access treatment',
    type: 'ADA',
    stack: 'J',
    status: 'PENDING',
    filingDate: '2026-05-20',
    clerkNote: 'Operative accommodation filing; requests ADA / Rule 1.100 processing and e-filing access treatment.',
    priority: 'CRITICAL',
  },
  {
    docNumber: '094-R1/R2',
    title: 'Combined Electronic Submission / Distribution Notice',
    shortDescription: 'Expanded routing, ADA coordinator notice, and written-response request',
    type: 'NOT',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-20',
    clerkNote: 'Provides expanded routing, ADA coordinator notice, and written-response request.',
    priority: 'CRITICAL',
  },
  {
    docNumber: '072',
    title: 'Master Gateway Index',
    shortDescription: 'Gateway orientation for ADA accommodation, e-filing compliance, and full defense record',
    type: 'GTW',
    stack: 'J',
    status: 'EXECUTED',
    filingDate: '2026-05-19',
    clerkNote: 'Gateway filing for ADA accommodation, e-filing compliance, and full 72-document defense record orientation.',
    priority: 'CRITICAL',
  },
  
  // STACK A — ANSWER & INITIAL PLEADINGS
  {
    docNumber: '01',
    title: 'Answer to Complaint for Unlawful Detainer',
    shortDescription: '13 affirmative defenses: retaliatory eviction (CC §1942.5), disability discrimination/failure to accommodate (ADA/FEHA), lack of subject matter jurisdiction (federal enclave — Presidio Trust), breach of habitability (CC §1941.1), constructive eviction, waiver/estoppel, unclean hands, witness tampering/abuse of process (42 USC §1512), Bane Act (CC §52.1), elder/dependent adult abuse (W&I §15657), active regulatory preemption (HHS-OCR 25-621293 / CRD 202601-33270627), City of SF nexus / VALORAIPLUS® protected tech, Fair Housing Act / FEHA. Filed May 17, 2026. Signed and witnessed by Jeffrey Wright (VTU).',
    type: 'ANS',
    stack: 'A',
    status: 'FILED',
    filingDate: '2026-05-17',
    priority: 'CRITICAL',
    relatedDocs: ['02', '20', '17'],
  },
  {
    docNumber: '02',
    title: 'Declaration of Donald Ernest Gillson in Support of Answer and Affirmative Defenses',
    shortDescription: 'Sworn declaration covering: 100% disabled Navy veteran / Section 8 HCV participant; ADA service animal Jaxx (ID ADA-23627741); cockroach/rodent infestation (Blattella germanica) from Oct 2025; DBI Case 101003004371 filed Nov 19, 2025; facial chemical exposure burns (Exhibits H-1/H-2); Jaxx vector bite wounds (H-3/H-4); Exhibit G video per se uninhabitability; Elder abuse RO application filed Nov 17, 2025 — UD initiated 48 hrs later triggering §1942.5(a) presumption; Landrum lacked valid DRE license; defective 3-Day notice service (CCP §1162); counsel has zero firsthand knowledge of premises. CRD Intake 202601-33270627 / HHS-OCR 25-621293 / DBI 101003004371. Filed May 17-19, 2026.',
    type: 'DEC',
    stack: 'A',
    status: 'FILED',
    filingDate: '2026-05-17',
    priority: 'HIGH',
    relatedDocs: ['01', '21', '26', '26-B'],
  },
  {
    docNumber: '03',
    title: 'Proof of Service - Answer',
    shortDescription: 'Proof of service for answer filing',
    type: 'POS',
    stack: 'A',
    status: 'FILED',
    filingDate: '2026-05-17',
  },
  {
    docNumber: '04',
    title: 'Civil Case Cover Sheet',
    shortDescription: 'CM-010 case cover sheet for civil matter',
    type: 'CM-010',
    stack: 'A',
    status: 'FILED',
    filingDate: '2026-05-17',
  },
  {
    docNumber: '05',
    title: 'Civil Cross-Complaint',
    shortDescription: 'Cross-Complaint asserting retaliation, civil-rights violations, elder/dependent-adult abuse, witness interference, fraud, and related claims seeking damages exceeding $4,253,000.00',
    type: 'XCOMP',
    stack: 'A',
    status: 'FILED',
    filingDate: '2026-05-17',
    priority: 'HIGH',
  },

  // STACK B — EX PARTE STAY
  {
    docNumber: '06',
    title: 'Ex Parte Motion for Stay',
    shortDescription: 'Emergency motion to stay unlawful detainer proceedings',
    type: 'MOT',
    stack: 'B',
    status: 'FILED',
    filingDate: '2026-05-17',
  },
  {
    docNumber: '07',
    title: 'State Bar Disciplinary Referral — Exhibit 2 Back-Dating',
    shortDescription: 'Formal referral to State Bar for document manipulation and potential forgery of Exhibit 2 (backdating); Cal. Penal Code §115; CRPC Rule 3.4',
    type: 'DEC',
    stack: 'B',
    status: 'FILED',
    filingDate: '2026-05-17',
  },
  {
    docNumber: '08',
    title: 'Proposed Order - Stay',
    shortDescription: 'Proposed order granting stay of proceedings',
    type: 'ORD',
    stack: 'B',
    status: 'FILED',
    filingDate: '2026-05-17',
  },
  {
    docNumber: '09',
    title: 'SF Whistleblower Protection Program Notice / HUD-OIG Filing',
    shortDescription: 'Federal grant compliance audit notice; retaliation protection for Defendant and Tenant Union witnesses; 42 USC §3617; SF Admin Code §4.115',
    type: 'NOT',
    stack: 'B',
    status: 'FILED',
    filingDate: '2026-05-17',
  },
  {
    docNumber: '10',
    title: 'Memorandum of Points & Authorities - Stay',
    shortDescription: 'Legal memorandum supporting ex parte stay',
    type: 'MPA',
    stack: 'B',
    status: 'FILED',
    filingDate: '2026-05-17',
  },

  // STACK C — DEMURRER
  {
    docNumber: '11',
    title: 'Demurrer to Complaint',
    shortDescription: 'Demurrer challenging legal sufficiency of complaint',
    type: 'DEM',
    stack: 'C',
    status: 'FILED',
    filingDate: '2026-05-17',
  },
  {
    docNumber: '12',
    title: 'Notice of Demurrer',
    shortDescription: 'Notice of hearing on demurrer',
    type: 'NOT',
    stack: 'C',
    status: 'FILED',
    filingDate: '2026-05-17',
  },
  {
    docNumber: '13',
    title: 'Points & Authorities - Demurrer',
    shortDescription: 'Legal memorandum supporting demurrer',
    type: 'MPA',
    stack: 'C',
    status: 'FILED',
    filingDate: '2026-05-17',
  },
  {
    docNumber: '14',
    title: 'Meet and Confer Declaration',
    shortDescription: 'Declaration regarding meet and confer efforts',
    type: 'DEC',
    stack: 'C',
    status: 'FILED',
    filingDate: '2026-05-17',
  },
  {
    docNumber: '15',
    title: 'Proposed Order - Demurrer',
    shortDescription: 'Proposed order sustaining demurrer',
    type: 'ORD',
    stack: 'C',
    status: 'FILED',
    filingDate: '2026-05-17',
  },
  
  // STACK D — MOTION TO STRIKE & THRESHOLD MOTIONS
  {
    docNumber: '16',
    title: 'Motion to Strike',
    shortDescription: 'Motion to strike portions of complaint',
    type: 'MOT',
    stack: 'D',
    status: 'FILED',
    filingDate: '2026-05-17',
  },
  {
    docNumber: 'Memo',
    title: 'Strategic Legal Memorandum — Historical and Doctrinal Parallels',
    shortDescription: 'Four-tier defensive architecture: (I) Constitutional Threshold Bar — federal enclave preemption (Art. I §8 Cl.17); (II) Statutory Retaliation Shield (CC §1942.5); (III) Habitability/Substandard Dwelling Bar (H&S §17920.3); (IV) Federal Funding Integrity Compliance Bar (2 CFR §200.435). Historical Parallel 1: Dred Scott v. Sandford jurisdictional strategy — state court compelled to examine constitutional jurisdiction limits before merits. Historical Parallel 2: Admiral Rickover federal spending compliance matrix — financial isolation forcing institutional resistance costs onto private unrestricted capital. Distinguishing factor: 26-document conformed matrix synchronized across state court, CRD, and HHS-OCR within 48-hour operational window. Filed May 17, 2026.',
    type: 'MPA',
    stack: 'D',
    status: 'FILED',
    filingDate: '2026-05-17',
    relatedDocs: ['20', '01', '17'],
    priority: 'HIGH',
  },
  {
    docNumber: '17',
    title: 'Motion for Sanctions, Attorney Fee Disgorgement, and Civil Penalty Log',
    shortDescription: 'CCP §128.7 / CC §1942.5(h) / Gov §12989.2 / CCP §1021.5. Five grounds: (A) filing retaliatory action within 180-day bar post-RAR Nov 20, 2025; (B) back-dated Exhibit 2 / document forgery (PC §115); (C) witness retaliation against Wright/Bartlett/Lucian post-March 19 RO hearing; (D) physical assault by Landrum ratified by counsel; (E) obstruction of HHS-OCR/CRD active investigations. Civil penalty log: 4 retaliatory acts × $2,000 = $8,000. Full attorney fee disgorgement. State Bar referral re: CRPC Rules 3.1, 3.4, 8.4(c), 8.4(d) for Zanghi (320531) and White (297746). Filed May 17, 2026.',
    type: 'MOT',
    stack: 'D',
    status: 'FILED',
    filingDate: '2026-05-17',
    relatedDocs: ['23', '42', '070', '064'],
    priority: 'HIGH',
  },
  {
    docNumber: '18',
    title: 'Points & Authorities — Motion to Strike',
    shortDescription: 'Legal memorandum supporting motion to strike',
    type: 'MPA',
    stack: 'D',
    status: 'FILED',
    filingDate: '2026-05-17',
  },
  {
    docNumber: '19',
    title: 'Motion to Quash Service of 3-Day Notice',
    shortDescription: 'Motion to quash defective 3-Day Notice service and dismiss complaint for failure to comply with CCP §1162; jurisdictional predicate challenge filed May 17, 2026',
    type: 'MOT',
    stack: 'D',
    status: 'FILED',
    filingDate: '2026-05-17',
    priority: 'HIGH',
  },
  {
    docNumber: '19-R1',
    type: 'ORD',
    stack: 'D',
    status: 'FILED',
    filingDate: '2026-04-20',
  },
  {
    docNumber: '20',
    title: 'Pre-Hearing Procedural Briefing Notice and Multi-Agency Synchronization Record',
    shortDescription: 'CCP §§1162, 1166, 1167 / CC §1942.5 / 2 CFR §200.435 / Cal. Evid. Code §§451–452. Five non-discretionary threshold issues: (1) defective 3-Day Notice service (CCP §1162 / Liebovich); (2) federal enclave jurisdiction bar (Art. I §8 Cl.17); (3) statutory retaliation bar (§1942.5(a) — 180-day window); (4) verification defect (CCP §2015.5); (5) active federal/state civil rights preemption (HHS-OCR 25-621293 / CRD 202601-33270627). Forensic SMTP blockade: Nodes SMTP-01 through SMTP-06 — 178 consecutive days Nov 20, 2025–May 17, 2026; rejection token N7uA_6IQ0CiwQL2ibFQZog.us448. Federal grant compliance: 125–210 billable hours must be sourced from Plaintiff\'s unrestricted private capital under 2 CFR §200.435. Multi-agency simultaneous transmittal: Zanghi, White, HHS-OCR, CRD, Court, HUD-OIG. Filed May 17, 2026.',
    type: 'NOT',
    stack: 'D',
    status: 'FILED',
    filingDate: '2026-05-17',
    relatedDocs: ['19', '21', '23', '091-R2'],
    priority: 'HIGH',
  },
  
  // STACK E — ADA, HABITABILITY & CONTEXTUAL
  {
    docNumber: '21',
    title: 'Declaration and Exhibit Packet',
    shortDescription: 'Defendant declaration authenticating factual background, service defects, federal-enclave issue, ADA needs, and exhibit record (Exhibits A–F including Exhibit C: SMTP forensic record)',
    type: 'DEC',
    stack: 'E',
    status: 'FILED',
    filingDate: '2026-05-17',
    priority: 'HIGH',
  },
  {
    docNumber: '22',
    title: 'Clinical Verification Declaration',
    shortDescription: 'Medical verification supporting ADA accommodation requests',
    type: 'DEC',
    stack: 'E',
    status: 'FILED',
    filingDate: '2026-05-17',
  },
  {
    docNumber: '23',
    title: 'Supplemental Forensic Notice of SMTP 550 Events and Formal Demand to Cease Adverse Action',
    shortDescription: 'CCP §§1162, 128.7, 1010.6 / CC §1942.5 / Cal. Evid. §§1271, 1552 / FRE 901(b)(9) / 2 CFR §200.435. Five additional Mimecast SMTP-550 rejection events May 16–17, 2026: SMTP-07 ekim@stp-sf.org (EBu500zHN...), SMTP-08 elena.kim@stp-sf.org (JaGba5SM...), SMTP-09 jbradford@stp-sf.org (Bz3RnUqX...), SMTP-10 william.landrum@stp-sf.org (dFZwv1rR...), SMTP-11 jzanghi@swords-to-plowshares.org (KZCLSIZ_...). Combined SMTP record: Nodes SMTP-01 through SMTP-11 — systemic enterprise-wide blockade. Four independently fatal legal bars enumerated. CCP §128.7 safe harbor notice issued: continued prosecution without threshold ruling = sanctions motion. Filed May 17, 2026.',
    type: 'NOT',
    stack: 'E',
    status: 'FILED',
    filingDate: '2026-05-17',
    relatedDocs: ['20', '19', '21', '069'],
    priority: 'HIGH',
  },
  {
    docNumber: '24',
    title: 'Emergency Restraining Order Application',
    shortDescription: 'Emergency injunctive relief against verbal harassment and retaliatory interference with tenancy; Cal. Welf. & Inst. Code §15657.03; CCP §527',
    type: 'DEC',
    stack: 'E',
    status: 'FILED',
    filingDate: '2026-05-17',
  },
  {
    docNumber: '25',
    title: 'Inpatient Timeline Declaration',
    shortDescription: 'Declaration establishing timeline of medical treatment',
    type: 'DEC',
    stack: 'E',
    status: 'FILED',
    filingDate: '2026-05-17',
  },
  {
    docNumber: '26',
    title: 'Supplemental Notice of Video Evidence and Habitability Record',
    shortDescription: 'Notice preserving Exhibit G real-time video recording of active cockroach/rodent infestation establishing per se uninhabitability under H&S Code §17920.3; chemical exposure documentation',
    type: 'NOT',
    stack: 'E',
    status: 'FILED',
    filingDate: '2026-05-17',
  },
  {
    docNumber: '26-B',
    title: 'Forensic Medical and Chemical Injury Video Analysis',
    shortDescription: 'Supplemental forensic analysis of chemical injury (facial exposure burns Exhibits H-1/H-2), service animal Jaxx vector bite wounds (H-3/H-4), and Exhibit G video transmittal under Cal. Evid. §1552 / FRE 901(b)(9)',
    type: 'DEC',
    stack: 'E',
    status: 'FILED',
    filingDate: '2026-05-17',
  },
  {
    docNumber: '27',
    title: 'Actual Knowledge and ADA Interactive Process Declaration',
    shortDescription: 'Declaration documenting actual knowledge of accommodation requests (RAR Nov 20, 2025 — GMAIL-02-RAR) and unilateral termination of ADA/FEHA mandatory interactive process; VALORAIPLUS® OMEGA v100™ N.E.W.T.™ cognitive prosthetic denial documented',
    type: 'DEC',
    stack: 'E',
    status: 'FILED',
    filingDate: '2026-05-17',
    priority: 'HIGH',
  },
  
  // STACK F — MOTION TO QUASH & SERVICE DEFECTS
  {
    docNumber: '28',
    title: 'Motion to Quash Service of Summons',
    shortDescription: 'Motion challenging service and jurisdiction, including federal-enclave and personal-jurisdiction arguments',
    type: 'MOT',
    stack: 'F',
    status: 'FILED',
    filingDate: '2026-04-25',
    priority: 'CRITICAL',
  },
  {
    docNumber: '29-R2',
    title: 'Reissued Declaration re Kolby Losik',
    shortDescription: 'Reissued declaration concerning witness intimidation, unauthorized disclosure, supportive-services conduct',
    type: 'DEC',
    stack: 'F',
    status: 'FILED',
    filingDate: '2026-04-25',
    priority: 'HIGH',
  },
  {
    docNumber: '30',
    title: 'Request for Judicial Notice - Federal',
    shortDescription: 'Request for judicial notice of federal jurisdiction issues',
    type: 'RJN',
    stack: 'F',
    status: 'FILED',
    filingDate: '2026-04-25',
  },
  {
    docNumber: '31',
    title: 'Points & Authorities - Quash',
    shortDescription: 'Legal memorandum supporting motion to quash',
    type: 'MPA',
    stack: 'F',
    status: 'FILED',
    filingDate: '2026-04-25',
  },
  {
    docNumber: '32',
    title: 'Exhibit G Video Transmittal',
    shortDescription: 'Exhibit cover sheet for video evidence transmittal',
    type: 'EXH',
    stack: 'F',
    status: 'FILED',
    filingDate: '2026-04-25',
  },
  {
    docNumber: '33',
    title: 'Service Defect Declaration',
    shortDescription: 'Declaration documenting defects in service of process',
    type: 'DEC',
    stack: 'F',
    status: 'FILED',
    filingDate: '2026-04-25',
  },
  {
    docNumber: '34',
    title: 'Proof of Service - Firewall',
    shortDescription: 'Proof of service documenting communication barriers',
    type: 'POS',
    stack: 'F',
    status: 'FILED',
    filingDate: '2026-04-25',
  },
  
  // STACK G — COMPLAINTS & CROSS-COMPLAINT
  {
    docNumber: '35',
    title: 'DRE Complaint',
    shortDescription: 'Complaint filed with Department of Real Estate',
    type: 'COMP',
    stack: 'G',
    status: 'FILED',
    filingDate: '2026-04-28',
  },
  {
    docNumber: '36',
    title: 'BBS Complaint',
    shortDescription: 'Complaint filed with Board of Behavioral Sciences',
    type: 'DEC',
    stack: 'G',
    status: 'FILED',
    filingDate: '2026-04-28',
  },
  {
    docNumber: '37',
    title: 'Cross-Complaint',
    shortDescription: 'Cross-complaint against plaintiff and related parties',
    type: 'XCOMP',
    stack: 'G',
    status: 'FILED',
    filingDate: '2026-04-28',
  },
  {
    docNumber: '38',
    title: 'Notice of Lodging',
    shortDescription: 'Notice of lodging for cross-complaint materials',
    type: 'NOT',
    stack: 'G',
    status: 'FILED',
    filingDate: '2026-04-28',
  },
  
  // STACK H — EVIDENCE INDEX & MOTIONS
  {
    docNumber: '39',
    title: 'Evidence Index',
    shortDescription: 'Master index of all evidence filed in the case',
    type: 'IDX',
    stack: 'H',
    status: 'FILED',
    filingDate: '2026-05-01',
  },
  {
    docNumber: '40',
    title: 'Motion - Statutory Presumption Retaliation',
    shortDescription: 'Motion establishing statutory presumption of retaliation',
    type: 'MOT',
    stack: 'H',
    status: 'FILED',
    filingDate: '2026-05-01',
    priority: 'HIGH',
  },
  {
    docNumber: '41',
    title: 'Supplemental Facts Declaration',
    shortDescription: 'Declaration providing supplemental facts for motions',
    type: 'DEC',
    stack: 'H',
    status: 'FILED',
    filingDate: '2026-05-01',
  },
  {
    docNumber: '42',
    title: 'Motion to Dismiss - Fraud on Court and Void Notice',
    shortDescription: 'Motion seeking dismissal based on void 3-day notice, fraud on the court, unlicensed property-management issue, and sanctions',
    type: 'MOT',
    stack: 'H',
    status: 'FILED',
    filingDate: '2026-05-01',
    priority: 'CRITICAL',
  },
  {
    docNumber: '43',
    title: 'Notice of Master Evidence Depository',
    shortDescription: 'Notice establishing master evidence repository location',
    type: 'NOT',
    stack: 'H',
    status: 'FILED',
    filingDate: '2026-05-01',
  },
  
  // STACK EXT — EXTENDED NOTICES
  {
    docNumber: '44',
    title: 'Notice of Service Failure',
    shortDescription: 'Notice documenting service delivery failures',
    type: 'NOT',
    stack: 'EXT',
    status: 'FILED',
    filingDate: '2026-05-03',
  },
  {
    docNumber: '45',
    title: 'Notice of Filing and Lodging',
    shortDescription: 'Notice of filing for extended materials',
    type: 'NOT',
    stack: 'EXT',
    status: 'LODGED',
    filingDate: '2026-05-03',
    clerkNote: 'LODGED — PENDING DOCKET',
  },
  {
    docNumber: '46',
    title: 'Master Bundle v5',
    shortDescription: 'Consolidated master bundle proof of service',
    type: 'POS',
    stack: 'EXT',
    status: 'LODGED',
    filingDate: '2026-05-03',
    clerkNote: 'LODGED — PENDING DOCKET',
  },
  
  // STACK I — EXHIBITS (Regulatory & Environmental)
  {
    docNumber: '47',
    title: 'Exhibit A-48-1: Regulatory Non-Compliance',
    shortDescription: 'Exhibit documenting regulatory non-compliance issues',
    type: 'EXH',
    stack: 'I',
    status: 'LODGED',
    filingDate: '2026-05-05',
    clerkNote: 'LODGED — PENDING DIRECTORY',
  },
  {
    docNumber: '48',
    title: 'Exhibit A-48-2: Environmental Hazard',
    shortDescription: 'Exhibit documenting environmental hazard conditions',
    type: 'EXH',
    stack: 'I',
    status: 'LODGED',
    filingDate: '2026-05-05',
    clerkNote: 'LODGED — PENDING DIRECTORY',
  },
  {
    docNumber: '49',
    title: 'Exhibit A-48-3: Infestation Density',
    shortDescription: 'Exhibit documenting pest infestation conditions',
    type: 'EXH',
    stack: 'I',
    status: 'LODGED',
    filingDate: '2026-05-05',
    clerkNote: 'LODGED — PENDING DIRECTORY',
  },
  {
    docNumber: '50',
    title: 'Exhibit A-48-4: Investigative Data Stromberg',
    shortDescription: 'Exhibit containing investigative data and analysis',
    type: 'EXH',
    stack: 'I',
    status: 'LODGED',
    filingDate: '2026-05-05',
    clerkNote: 'LODGED — PENDING DIRECTORY',
  },
  {
    docNumber: '51',
    title: 'Exhibit A-48-5: Medical Coordination',
    shortDescription: 'Exhibit documenting medical coordination issues',
    type: 'EXH',
    stack: 'I',
    status: 'LODGED',
    filingDate: '2026-05-05',
    clerkNote: 'LODGED — PENDING DIRECTORY',
  },
  
  // STACK J — FORENSIC DOSSIER & CURRENT CAMPAIGN
  {
    docNumber: '50',
    title: 'ADA Accommodation Compliance Notice',
    shortDescription: 'ADA notice requesting written acknowledgment, accessible filing methods, remote appearance, fee accommodation',
    type: 'ADA',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-06',
  },
  {
    docNumber: '56',
    title: 'Consolidated Forensic Dossier',
    shortDescription: 'Master forensic analysis and evidence compilation',
    type: 'DEC',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-08',
    priority: 'HIGH',
  },
  {
    docNumber: '57',
    title: 'Fee Waiver Application (FW-001)',
    shortDescription: 'Fee-waiver application based on public-benefit status, financial hardship, and access-to-court concerns',
    type: 'FW-001',
    stack: 'J',
    status: 'PENDING',
    filingDate: '2026-05-08',
    clerkNote: 'PENDING JUDICIAL RULING',
    priority: 'HIGH',
  },
  {
    docNumber: '58',
    title: 'ADA Accommodation Request',
    shortDescription: 'Formal ADA accommodation request under Rule 1.100',
    type: 'ADA',
    stack: 'J',
    status: 'PENDING',
    filingDate: '2026-05-08',
    clerkNote: 'PENDING JUDICIAL RULING',
  },
  {
    docNumber: '59',
    title: 'Notice of Lodging and Transmittal of Documents 56-58',
    shortDescription: 'Notice of lodging for documents 56 through 58',
    type: 'NOT',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-10',
  },
  {
    docNumber: '60',
    title: 'Administrative Contradiction and Continued Tenancy Notice',
    shortDescription: 'Notice arguing inspection scheduling and administrative treatment contradict unlawful-detainer posture',
    type: 'NOT',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-10',
    priority: 'HIGH',
  },
  {
    docNumber: '61',
    title: 'Supplemental Declaration - Misnaming Retaliation',
    shortDescription: 'Declaration documenting misnaming and retaliation patterns',
    type: 'DEC',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-10',
  },
  {
    docNumber: '62',
    title: 'Motion to Reconsider TRO - EDAA',
    shortDescription: 'Motion to reconsider temporary restraining order under Elder/Dependent Adult Abuse Act',
    type: 'MOT',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-12',
  },
  {
    docNumber: '63',
    title: 'Internal Grievance - Admin Exhaustion STP',
    shortDescription: 'Internal grievance for administrative exhaustion with Swords to Plowshares',
    type: 'GRIEV',
    stack: 'J',
    status: 'ACTIVE',
    filingDate: '2026-05-12',
    clerkNote: 'ACTIVE — 10-DAY CLOCK RUNNING',
  },
  {
    docNumber: '64',
    title: 'Statement of Bad Faith Litigation Conduct',
    shortDescription: 'Pattern of procedural abuse by Swords to Plowshares and Zanghi; request for CCP §§ 128.5/128.7 sanctions, terminating sanctions, and State Bar referral based on 64-filing silence doctrine and Mimecast blocking',
    type: 'MOT',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-19',
    relatedDocs: ['042', '070', '069'],
    priority: 'HIGH',
  },
  {
    docNumber: '65',
    title: 'Denial of Reasonable Accommodations Chronological Record',
    shortDescription: 'Chronological record of ADA/FHA accommodation denials and failures to engage in interactive process',
    type: 'DEC',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-14',
    priority: 'HIGH',
  },
  {
    docNumber: '66',
    title: 'Constructive Eviction — Two-Period Chronological Record',
    shortDescription: 'Period I (Nov 19–Dec 23, 2025): cockroach infestation and administrative abandonment. Period II (Feb 24–May 20, 2026): retaliatory campaign — service withdrawal, unauthorized entry, clinical intimidation, Mimecast technical isolation. Both periods independently establish Green v. Superior Court defense.',
    type: 'DEC',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-19',
    relatedDocs: ['065', '070', '042'],
    priority: 'HIGH',
  },
  {
    docNumber: '67',
    title: 'Notice of Document Fraud - Backdated Notice to Quit',
    shortDescription: 'Notice alleging backdated or falsified notice to quit documents',
    type: 'NOT',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-14',
  },
  {
    docNumber: '68',
    title: 'Omnibus Transmittal - Mimecast Log - Notice of Lodgment',
    shortDescription: 'Omnibus notice including Mimecast forensic log and lodgment notice',
    type: 'NOT',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-15',
  },
  {
    docNumber: '69',
    title: 'Amended Clerk-Direct Hard Block and Manual Lodgment Notice',
    shortDescription: 'Amended notice of court e-filing hard block combined with 9-address Mimecast 550 Administrative Prohibition registry (Docs 64–70 blocked); demand for manual lodgment; ADA Title II § 12132 access violation; referral to Rule 1.100 ADA Coordinator',
    type: 'NOT',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-19',
    clerkNote: 'MANUAL LODGMENT DEMANDED — 9-ADDRESS MIMECAST BLOCK CONFIRMED',
    relatedDocs: ['068', '092', '094-R1/R2'],
    priority: 'HIGH',
  },
  {
    docNumber: '70',
    title: 'Retaliatory Campaign by Landrum — Five-Act Chronological Record',
    shortDescription: 'Five retaliatory acts by William Landrum (late Feb–Mar 1, 2026): (1) backdated 3-Day NTQ; (2) public hallway posting of PII; (3) false SFHA perjury attestation misidentifying TRO respondent; (4) erasure of Landrum name/substitution of Bradford on UD filing; (5) false 5150 psychiatric hold attempt via Travis AFB targeting service animal',
    type: 'DEC',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-19',
    relatedDocs: ['042', '074', '075', '076'],
    priority: 'CRITICAL',
  },
  {
    docNumber: '71',
    title: 'Master Index Cover Sheet Finalized',
    shortDescription: 'Finalized cover sheet for master document index',
    type: 'IDX',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-18',
  },
  {
    docNumber: '074',
    title: 'Notice of Related Case and Cross-Lodgment',
    shortDescription: 'Notice to Dept. 12 that the 3-Day NTQ was issued by the named respondent in active elder/dependent adult abuse RO case CCH-28-589086; five-element related-case analysis under Cal. Rules of Court Rule 3.300; request for judicial coordination and cross-lodgment of RO record into CUD',
    type: 'NOT',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-19',
    relatedDocs: ['042', '070', '075'],
    priority: 'CRITICAL',
  },
  {
    docNumber: '075',
    title: 'Notice to Judge Tong — RO Primary Cross-Reference to CUD Case',
    shortDescription: 'Direct notice to Hon. Judge Tong under CCH-28-589086 docket: Landrum (RO respondent) is also the originating actor in CUD-26-682107; five post-March 19 retaliation acts documented; request for RO enforcement, cross-case judicial notice, UD dismissal with prejudice, and DA referral for perjury/false report',
    type: 'NOT',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-19',
    relatedDocs: ['074', '076', '070', '042'],
    priority: 'CRITICAL',
  },
  {
    docNumber: '076',
    title: 'Notice of Fraud Upon the Court — Zanghi False Representation at March 19 Hearing',
    shortDescription: 'Notice that counsel Zanghi misrepresented to Judge Tong at the Mar 19, 2026 RO hearing that: (1) no UD was pending, and (2) he did not represent Swords to Plowshares — both false; dual conflict-of-interest analysis (RPOC Rules 1.7, 3.3, 8.4); request for OSC, sanctions, disqualification, and State Bar referral',
    type: 'NOT',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-19',
    relatedDocs: ['075', '042', '070'],
    priority: 'CRITICAL',
  },
  {
    docNumber: '079',
    title: 'IP Theft / ESI Preservation Notice',
    shortDescription: 'Notice adding trade-secret/IP theft theory and requesting ESI preservation regarding VALORAIPLUS',
    type: 'NOT',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-19',
  },
  {
    docNumber: '078',
    title: 'Omnibus ADA, Elder Abuse, and Mandated Reporter Notice',
    shortDescription: 'Omnibus notice: 8-count ADA Title II violation record (ADA-01 through ADA-08); 4-count financial elder/dependent adult abuse record (FA-01 through FA-04); individual liability notice to 30+ named persons and entities; formal mandated reporter demand to court clerk under W&I Code § 15630; referral to APS and DA',
    type: 'NOT',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-21',
    relatedDocs: ['065', '075', '076', '027'],
    priority: 'CRITICAL',
  },
  {
    docNumber: '085',
    title: 'Declaration: Node Map, Residential Address, and Business Entity Designations',
    shortDescription: 'First formal notice to Court of Defendant\'s complete operational Node Map: (1) San Francisco Node — address of record/subject property; (2) Sunnyvale Node — IP/tech ops, That\'s Edutainment LLC and 32D LLC, ValorAI+; (3) Los Gatos Node — storage/records; (4) Palo Alto Node — VA Medical, disability docs; (5) Monterey Node — secondary business ops. DTSA, CUTSA, CFAA trade-secret situs declaration',
    type: 'DEC',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-21',
    relatedDocs: ['079', '080'],
    priority: 'HIGH',
  },
  {
    docNumber: '080',
    title: 'Omnibus Final Filing',
    shortDescription: 'Master closing filing consolidating all asserted causes of action and requested relief',
    type: 'MOT',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-20',
    priority: 'HIGH',
  },
  {
    docNumber: '081',
    title: 'Motion to Consolidate',
    shortDescription: 'Motion to consolidate related CUD and CCH proceedings based on common parties, facts, witnesses',
    type: 'MOT',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-20',
  },
  {
    docNumber: '082',
    title: 'Non-Party Stakeholder Notice',
    shortDescription: 'Notice of service to non-party stakeholders and request for docket entry',
    type: 'NOT',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-20',
  },
  {
    docNumber: '083',
    title: 'Cross-Lodgment Notice',
    shortDescription: 'Notice confirming cross-lodgment of consolidation motion into related CCH case',
    type: 'NOT',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-20',
  },
  {
    docNumber: '084',
    title: 'Corporate Malfeasance Notice',
    shortDescription: 'Notice alleging corporate malfeasance, bad-faith litigation conduct, and grounds for OSC or dismissal',
    type: 'NOT',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-21',
  },
  {
    docNumber: '087',
    title: 'Federal Grant Misuse Notice',
    shortDescription: 'Notice alleging misuse of federal housing/veteran-support funding under ADA/FHA/Section 504 theories',
    type: 'NOT',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-21',
    priority: 'HIGH',
  },
  {
    docNumber: '089-R2',
    title: 'Amended Motion to Compel Financial Disclosure — Retainer, Insurance, and Bonding',
    shortDescription: 'Amended motion (expands Doc 088) demanding disclosure of Plaintiff\'s liability insurance carriers, surety/bonding entities, and a verified declaration from Landrum explaining refusal to provide insurance info to State Farm re: Audi Q5 incident and cockroach infestation property-damage claims; CCP § 2017.210',
    type: 'MOT',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-21',
    relatedDocs: ['088', '066', '076'],
    priority: 'HIGH',
  },
  {
    docNumber: '090-R2',
    title: 'Filing / POS Addendum',
    shortDescription: 'Corrected filing and proof-of-service addendum identifying additional index materials',
    type: 'POS',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-22',
  },
  {
    docNumber: '091-R2',
    title: 'Notice of Willful Regulatory Non-Compliance — Formal Demand for Corrective Action and Voluntary Dismissal',
    shortDescription: '7-count predicate non-compliance record (ADA/FEHA failure, Mimecast obstruction, Zanghi misrepresentation, backdated NTQ, insurance obstruction, retaliatory eviction, service withdrawal); regulatory sync table (HHS-OCR 25-621293, CRD 202601-33270627, CalVCB A26-10224054, SFHRC, SFW, SFDA); 10-day demand for voluntary dismissal with prejudice, retainer/insurance production, cessation of retaliation against VTU members',
    type: 'NOT',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-22',
    relatedDocs: ['068', '076', '067', '088', '089-R2', '056'],
    priority: 'CRITICAL',
    clerkNote: 'FORMAL DEMAND — 10-DAY CURE PERIOD INITIATED MAY 22, 2026',
  },
  {
    docNumber: '096',
    title: 'Statement of Facts',
    shortDescription: 'Core statement supporting affirmative defenses, accommodation record, jurisdictional challenge',
    type: 'DEC',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-23',
    priority: 'HIGH',
  },
  {
    docNumber: '099-R1',
    title: 'Amended Request for Judicial Notice — Court-Readability Index and Forensic Repository Orientation',
    shortDescription: 'Amended RJN orienting the Court to the 32-document priority matrix; four threshold issues (retaliation/pretext, disability access, procedural defects/ESI, witness notice chain); judicial economy focus; court-safe terminology matrix; Master Filing Locker link; notice of distinction between formal service and courtesy transmissions',
    type: 'RJN',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-24',
    relatedDocs: ['000-AA0-R1', '092', '102', '102-R2', '103-R1'],
    priority: 'HIGH',
    clerkNote: 'OPEN FIRST — Court orientation document for the 32-document priority tranche',
  },
  {
    docNumber: '102',
    title: 'Amendment to Statement of Facts / Preservation Record',
    shortDescription: 'Amendment confirming priority filing tranche, preservation of staged materials, and non-abandonment of prior RapidLegal / LegalConnect staged documents',
    type: 'NOT',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-24',
  },
  {
    docNumber: '102-R2',
    title: 'Targeted Veterans / VTU Retaliation Notice',
    shortDescription: 'Notice identifying Jeff Wright, Jerry Bartlett, Dan Lucian as affected witnesses or targeted veteran tenants',
    type: 'NOT',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-24',
    priority: 'HIGH',
  },
  {
    docNumber: '103-R1',
    title: 'Courtesy Transmission / Witness Preservation Notice',
    shortDescription: 'Notice preserving text-message courtesy transmissions, witness identification, related-tenant contacts',
    type: 'NOT',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-24',
  },
  {
    docNumber: '106',
    title: 'FBI San Francisco Notice',
    shortDescription: 'Agency-intake and evidence-preservation notice regarding court-access obstruction, ADA/housing retaliation',
    type: 'NOT',
    stack: 'J',
    status: 'FILED',
    filingDate: '2026-05-24',
    priority: 'CRITICAL',
  },
];

// ─── RapidLegal Upload Order ───────────────────────────────────────────────
// 33-item judge-readable sequenced upload order generated May 24, 2026.
// Logic: 1. Court-readability/roadmap → 2. ADA access/preservation →
//        3. Witness/agency/VTU preservation → 4. Factual declarations →
//        5. Dispositive/procedural motions → 6. Forensic chronologies →
//        7. Related-case notices → 8. Final compliance/distribution notices

export interface RapidLegalEntry {
  uploadOrder: number;
  docNumber: string;
  title: string;
  category: string;
}

export const RAPIDLEGAL_UPLOAD_ORDER: RapidLegalEntry[] = [
  { uploadOrder: 1,  docNumber: '099-R1',     title: 'Amended Request for Judicial Notice / Court-Readability Index',              category: 'Court Readability / Roadmap' },
  { uploadOrder: 2,  docNumber: '000-AA0-R1', title: 'Lead Clerk Filing Statement / Master Repository Roadmap',                    category: 'Court Readability / Roadmap' },
  { uploadOrder: 3,  docNumber: '092',         title: 'Electronic MC-410 / Reasonable Accommodation / UD-105 Affirmative Defenses', category: 'ADA Access & Preservation' },
  { uploadOrder: 4,  docNumber: '102',         title: 'Amendment to Statement of Facts / Preservation Record',                     category: 'ADA Access & Preservation' },
  { uploadOrder: 5,  docNumber: '102-R2',      title: 'Targeted Veterans / VTU Retaliation Notice',                                category: 'Witness / Agency / VTU Preservation' },
  { uploadOrder: 6,  docNumber: '103-R1',      title: 'Courtesy Transmission / Witness Preservation Notice',                      category: 'Witness / Agency / VTU Preservation' },
  { uploadOrder: 7,  docNumber: '106',         title: 'FBI San Francisco Notice',                                                  category: 'Witness / Agency / VTU Preservation' },
  { uploadOrder: 8,  docNumber: '02',          title: 'Declaration of Donald Ernest Gillson',                                      category: 'Factual Declarations' },
  { uploadOrder: 9,  docNumber: 'Memo',        title: 'Strategic Legal Memorandum — Historical and Doctrinal Parallels R2',        category: 'Factual Declarations' },
  { uploadOrder: 10, docNumber: '20',          title: 'Pre-Hearing Procedural Briefing Notice R2',                                 category: 'Factual Declarations' },
  { uploadOrder: 11, docNumber: '21',          title: 'Declaration and Exhibit Packet R2',                                         category: 'Factual Declarations' },
  { uploadOrder: 12, docNumber: '27',          title: 'Actual Knowledge and ADA Interactive Process Declaration',                  category: 'Factual Declarations' },
  { uploadOrder: 13, docNumber: '28',          title: 'Motion to Quash Service of Summons',                                       category: 'Dispositive & Procedural Motions' },
  { uploadOrder: 14, docNumber: '29-R2',       title: 'Reissued Declaration re Kolby Losik',                                      category: 'Factual Declarations' },
  { uploadOrder: 15, docNumber: '42',          title: 'Motion to Dismiss / Fraud on Court / Void Notice',                         category: 'Dispositive & Procedural Motions' },
  { uploadOrder: 16, docNumber: '56',          title: 'Consolidated Forensic Dossier',                                            category: 'Forensic Chronologies' },
  { uploadOrder: 17, docNumber: '57B',         title: 'Omnibus Notice / Reasonable Accommodation / New Evidence R2',              category: 'ADA Access & Preservation' },
  { uploadOrder: 18, docNumber: '59',          title: 'Notice of Lodging and Transmittal of Docs 56–58',                          category: 'Forensic Chronologies' },
  { uploadOrder: 19, docNumber: '60',          title: 'Administrative Contradiction and Continued Tenancy Notice',                category: 'Forensic Chronologies' },
  { uploadOrder: 20, docNumber: '64',          title: 'Bad Faith Litigation Conduct Summary Statement R2',                        category: 'Dispositive & Procedural Motions' },
  { uploadOrder: 21, docNumber: '65',          title: 'Denial of Reasonable Accommodations Chronological Record R2',              category: 'Forensic Chronologies' },
  { uploadOrder: 22, docNumber: '66',          title: 'Constructive Eviction Chronological Record R2',                            category: 'Forensic Chronologies' },
  { uploadOrder: 23, docNumber: '69',          title: 'Amended Clerk-Direct Hard Block / Manual Lodgment Notice',                 category: 'ADA Access & Preservation' },
  { uploadOrder: 24, docNumber: '70',          title: 'Retaliatory Campaign by Landrum Chronological Record R2',                  category: 'Forensic Chronologies' },
  { uploadOrder: 25, docNumber: '72',          title: 'Master Gateway Index',                                                     category: 'Court Readability / Roadmap' },
  { uploadOrder: 26, docNumber: '074',         title: 'Notice of Related Case and Cross-Lodgment R2',                             category: 'Related-Case Notices' },
  { uploadOrder: 27, docNumber: '075',         title: 'Judge Tong RO Primary Cross-Reference to CUD Case R2',                    category: 'Related-Case Notices' },
  { uploadOrder: 28, docNumber: '076',         title: 'Zanghi False Representation / March 19 Hearing R2',                       category: 'Related-Case Notices' },
  { uploadOrder: 29, docNumber: '078',         title: 'Omnibus ADA, Elder Abuse, and Mandated Reporter Notice R2',                category: 'Final Compliance / Distribution' },
  { uploadOrder: 30, docNumber: '085',         title: 'Declaration Node Map / Residential Address / Business Nodes R2',           category: 'Factual Declarations' },
  { uploadOrder: 31, docNumber: '089-R2',      title: 'Amended Motion to Compel Financial Disclosure / Retainer',                 category: 'Dispositive & Procedural Motions' },
  { uploadOrder: 32, docNumber: '091-R2',      title: 'Notice of Willful Regulatory Non-Compliance',                              category: 'Final Compliance / Distribution' },
  { uploadOrder: 33, docNumber: '094-R1/R2',   title: 'Final Notice Expanded Distribution / MC-410 / ADA E-Filing',              category: 'Final Compliance / Distribution' },
];

export const RAPIDLEGAL_CATEGORIES = [
  'Court Readability / Roadmap',
  'ADA Access & Preservation',
  'Witness / Agency / VTU Preservation',
  'Factual Declarations',
  'Dispositive & Procedural Motions',
  'Forensic Chronologies',
  'Related-Case Notices',
  'Final Compliance / Distribution',
] as const;

export const RAPIDLEGAL_CATEGORY_COLORS: Record<string, { bg: string; text: string; border: string }> = {
  'Court Readability / Roadmap':          { bg: 'bg-primary/20',       text: 'text-primary',          border: 'border-primary/40' },
  'ADA Access & Preservation':            { bg: 'bg-emerald-500/20',   text: 'text-emerald-500',      border: 'border-emerald-500/40' },
  'Witness / Agency / VTU Preservation':  { bg: 'bg-cyan-500/20',      text: 'text-cyan-500',         border: 'border-cyan-500/40' },
  'Factual Declarations':                 { bg: 'bg-blue-500/20',      text: 'text-blue-500',         border: 'border-blue-500/40' },
  'Dispositive & Procedural Motions':     { bg: 'bg-destructive/20',   text: 'text-destructive',      border: 'border-destructive/40' },
  'Forensic Chronologies':                { bg: 'bg-amber-500/20',     text: 'text-amber-500',        border: 'border-amber-500/40' },
  'Related-Case Notices':                 { bg: 'bg-violet-500/20',    text: 'text-violet-500',       border: 'border-violet-500/40' },
  'Final Compliance / Distribution':      { bg: 'bg-orange-500/20',    text: 'text-orange-500',       border: 'border-orange-500/40' },
};

// Utility functions
export function getDocumentsByStack(stack: Stack): CaseDocument[] {
  return CASE_DOCUMENTS.filter(doc => doc.stack === stack);
}

export function getDocumentsByStatus(status: DocStatus): CaseDocument[] {
  return CASE_DOCUMENTS.filter(doc => doc.status === status);
}

export function getDocumentsByType(type: DocType): CaseDocument[] {
  return CASE_DOCUMENTS.filter(doc => doc.type === type);
}

export function getPriorityDocuments(): CaseDocument[] {
  return CASE_DOCUMENTS.filter(doc => doc.priority === 'CRITICAL' || doc.priority === 'HIGH');
}

export function searchDocuments(query: string): CaseDocument[] {
  const lowerQuery = query.toLowerCase();
  return CASE_DOCUMENTS.filter(doc => 
    doc.title.toLowerCase().includes(lowerQuery) ||
    doc.shortDescription.toLowerCase().includes(lowerQuery) ||
    doc.docNumber.toLowerCase().includes(lowerQuery) ||
    doc.type.toLowerCase().includes(lowerQuery)
  );
}

export function getRecordSummary() {
  const total = CASE_DOCUMENTS.length;
  const filed = CASE_DOCUMENTS.filter(d => d.status === 'FILED').length;
  const pending = CASE_DOCUMENTS.filter(d => d.status === 'PENDING').length;
  const lodged = CASE_DOCUMENTS.filter(d => d.status === 'LODGED').length;
  const active = CASE_DOCUMENTS.filter(d => d.status === 'ACTIVE').length;
  const executed = CASE_DOCUMENTS.filter(d => d.status === 'EXECUTED').length;
  
  return { total, filed, pending, lodged, active, executed };
}
