/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  VALORAIPLUS_NULL_GHOST,
  VALORAIPLUS_NULL_GHOSTInterface,
} from "../../contracts/VALORAIPLUS_NULL_GHOST";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "get_root",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "node_hash",
        type: "bytes32",
      },
    ],
    name: "verify_standing",
    outputs: [
      {
        internalType: "bytes32",
        name: "status",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60808060405234601657335f5560db9081601b8239f35b5f80fdfe608060405260043610156010575f80fd5b5f3560e01c8063a30c5f171460775763abb4808b14602c575f80fd5b3460735760203660031901126073577fbc3a567d2e8f1a4b9c0d2e4f6a8b0c2d4e6f8a0b2c4d6e8f0a2b4c6d8e0f1a2b60043514606e5760206040515f198152f35b60205ff35b5f80fd5b346073575f3660031901126073577226856b24c50750f0c69c1eeb86a69ef777777760681b60805260206080f3fea26469706673582212206d53e1fdd6ee6e81f6dbc25f935823a7d262d418785205b9da17c4f5b886f07764736f6c634300081a0033";

type VALORAIPLUS_NULL_GHOSTConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: VALORAIPLUS_NULL_GHOSTConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class VALORAIPLUS_NULL_GHOST__factory extends ContractFactory {
  constructor(...args: VALORAIPLUS_NULL_GHOSTConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      VALORAIPLUS_NULL_GHOST & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): VALORAIPLUS_NULL_GHOST__factory {
    return super.connect(runner) as VALORAIPLUS_NULL_GHOST__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): VALORAIPLUS_NULL_GHOSTInterface {
    return new Interface(_abi) as VALORAIPLUS_NULL_GHOSTInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): VALORAIPLUS_NULL_GHOST {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as VALORAIPLUS_NULL_GHOST;
  }
}
