-- supabase/migrations/20260525_create_traffic_tables.sql
-- Web traffic intelligence tracking schema

-- Page views table - captures every HTTP request
CREATE TABLE IF NOT EXISTS page_views (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  ip_address INET NOT NULL,
  user_agent TEXT NOT NULL,
  path TEXT NOT NULL,
  method TEXT NOT NULL DEFAULT 'GET',
  referer TEXT,
  country VARCHAR(100),
  city VARCHAR(100),
  device_type VARCHAR(20) NOT NULL DEFAULT 'unknown',
  browser VARCHAR(50),
  os VARCHAR(50),
  timestamp TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  response_time_ms INT,
  status_code SMALLINT,
  
  CONSTRAINT valid_status_code CHECK (status_code >= 100 AND status_code < 600),
  CONSTRAINT valid_device CHECK (device_type IN ('desktop', 'mobile', 'tablet', 'unknown'))
);

-- Sessions table - tracks user session data
CREATE TABLE IF NOT EXISTS sessions (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  session_id UUID NOT NULL DEFAULT gen_random_uuid(),
  ip_address INET NOT NULL,
  first_page TEXT NOT NULL,
  last_page TEXT NOT NULL,
  pages_visited INT NOT NULL DEFAULT 1,
  session_duration_seconds INT,
  entry_time TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  exit_time TIMESTAMP WITH TIME ZONE,
  user_agent TEXT NOT NULL,
  country VARCHAR(100),
  city VARCHAR(100),
  device_type VARCHAR(20) NOT NULL DEFAULT 'unknown',
  browser VARCHAR(50),
  os VARCHAR(50),
  
  CONSTRAINT unique_session UNIQUE (session_id),
  CONSTRAINT valid_device CHECK (device_type IN ('desktop', 'mobile', 'tablet', 'unknown'))
);

-- Unique visitors table - aggregated daily
CREATE TABLE IF NOT EXISTS daily_visitors (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  visitor_date DATE NOT NULL,
  unique_visitors INT NOT NULL DEFAULT 0,
  total_page_views INT NOT NULL DEFAULT 0,
  total_sessions INT NOT NULL DEFAULT 0,
  avg_session_duration_seconds NUMERIC,
  mobile_visitors INT DEFAULT 0,
  desktop_visitors INT DEFAULT 0,
  tablet_visitors INT DEFAULT 0,
  
  CONSTRAINT unique_daily UNIQUE (visitor_date)
);

-- Top pages table - aggregated by path
CREATE TABLE IF NOT EXISTS top_pages (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  path TEXT NOT NULL,
  view_count INT NOT NULL DEFAULT 0,
  unique_visitors INT NOT NULL DEFAULT 0,
  avg_response_time_ms NUMERIC,
  last_updated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  
  CONSTRAINT unique_path UNIQUE (path)
);

-- Visitor locations table - aggregated geolocation data
CREATE TABLE IF NOT EXISTS visitor_locations (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  country VARCHAR(100) NOT NULL,
  city VARCHAR(100),
  visitor_count INT NOT NULL DEFAULT 0,
  session_count INT NOT NULL DEFAULT 0,
  last_updated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  
  CONSTRAINT unique_location UNIQUE (country, city)
);

-- Create indexes for fast queries
CREATE INDEX idx_page_views_timestamp ON page_views(timestamp DESC);
CREATE INDEX idx_page_views_ip_address ON page_views(ip_address);
CREATE INDEX idx_page_views_path ON page_views(path);
CREATE INDEX idx_page_views_device_type ON page_views(device_type);
CREATE INDEX idx_sessions_session_id ON sessions(session_id);
CREATE INDEX idx_sessions_entry_time ON sessions(entry_time DESC);
CREATE INDEX idx_top_pages_view_count ON top_pages(view_count DESC);
CREATE INDEX idx_visitor_locations_country ON visitor_locations(country);

-- Enable Row Level Security
ALTER TABLE page_views ENABLE ROW LEVEL SECURITY;
ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_visitors ENABLE ROW LEVEL SECURITY;
ALTER TABLE top_pages ENABLE ROW LEVEL SECURITY;
ALTER TABLE visitor_locations ENABLE ROW LEVEL SECURITY;

-- Allow reads from authenticated users
CREATE POLICY "Allow read access to page_views for authenticated users"
  ON page_views FOR SELECT
  TO authenticated
  USING (TRUE);

CREATE POLICY "Allow read access to sessions for authenticated users"
  ON sessions FOR SELECT
  TO authenticated
  USING (TRUE);

CREATE POLICY "Allow read access to daily_visitors for authenticated users"
  ON daily_visitors FOR SELECT
  TO authenticated
  USING (TRUE);

CREATE POLICY "Allow read access to top_pages for authenticated users"
  ON top_pages FOR SELECT
  TO authenticated
  USING (TRUE);

CREATE POLICY "Allow read access to visitor_locations for authenticated users"
  ON visitor_locations FOR SELECT
  TO authenticated
  USING (TRUE);

-- Allow inserts from authenticated users and service role
CREATE POLICY "Allow inserts to page_views"
  ON page_views FOR INSERT
  TO authenticated, service_role
  WITH CHECK (TRUE);

CREATE POLICY "Allow inserts to sessions"
  ON sessions FOR INSERT
  TO authenticated, service_role
  WITH CHECK (TRUE);

CREATE POLICY "Allow inserts to daily_visitors"
  ON daily_visitors FOR INSERT
  TO authenticated, service_role
  WITH CHECK (TRUE);

CREATE POLICY "Allow inserts to top_pages"
  ON top_pages FOR INSERT
  TO authenticated, service_role
  WITH CHECK (TRUE);

CREATE POLICY "Allow inserts to visitor_locations"
  ON visitor_locations FOR INSERT
  TO authenticated, service_role
  WITH CHECK (TRUE);
