/**
 * AMath Hardened Dual-Boundary Runtime Architecture v2.0
 * 
 * Core Principle:
 *   runtime proves software behavior
 *   evidence proves external reality
 * 
 * This model creates strict separation between:
 *   - deterministic runtime observations
 *   - external claims requiring corroboration
 *   - interpretation layers
 *   - visualization surfaces
 */

// ============================================================
// CORROBORATION MODEL
// ============================================================

/**
 * Hardened Corroboration Status
 * 
 * | Status                | Meaning                        |
 * |-----------------------|--------------------------------|
 * | RUNTIME_VERIFIED      | Proven by code execution       |
 * | CORROBORATED          | Supported by external evidence |
 * | PENDING_CORROBORATION | Awaiting supporting material   |
 * | DISPUTED              | Evidence conflict exists       |
 * | UNVERIFIED            | No validation available        |
 */
export type CorroborationStatus =
  | 'RUNTIME_VERIFIED'
  | 'CORROBORATED'
  | 'PENDING_CORROBORATION'
  | 'DISPUTED'
  | 'UNVERIFIED';

// ============================================================
// RUNTIME PROVENANCE
// ============================================================

/**
 * Runtime Provenance Layer
 * 
 * Every runtime-confirmed result carries provenance.
 * Provenance prevents ambiguity.
 * 
 * Without provenance: "this happened"
 * With provenance: "this happened because runtime XYZ produced it under build ABC"
 */
export interface RuntimeProvenance {
  /** Build hash or commit SHA */
  buildHash: string;
  /** ISO timestamp of generation */
  generatedAt: string;
  /** Verification source */
  verifiedBy: 'build' | 'api' | 'runtime';
  /** Deployment environment */
  environment: 'dev' | 'preview' | 'production';
  /** Source route or module */
  routeSource: string;
  /** Optional integrity checksum */
  checksum?: string;
}

// ============================================================
// SOURCE CLASSIFICATION
// ============================================================

/**
 * Source Type Classification
 * 
 * - runtime: Generated by code execution
 * - external: From third-party systems
 * - manual: Human-entered data
 */
export type SourceType = 'runtime' | 'external' | 'manual';

// ============================================================
// EVIDENCE ROW MODEL
// ============================================================

/**
 * Hardened Evidence Row
 * 
 * All high-value tables include:
 *   sourceType
 *   corroboration
 *   lastReviewedAt
 *   provenance
 */
export interface EvidenceRow {
  id: string;
  label: string;
  value: string;
  sourceType: SourceType;
  corroboration: CorroborationStatus;
  lastReviewedAt: string;
  provenance?: RuntimeProvenance;
}

// ============================================================
// RECEIPT V2 MODEL
// ============================================================

/**
 * Hardened Receipt Layer
 * 
 * Receipt objects distinguish runtime proof from narrative context.
 */
export interface ReceiptV2 {
  receiptId: string;
  route: string;
  decision: string;
  generatedAt: string;

  /** Whether this receipt was generated by runtime execution */
  runtimeVerified: boolean;
  /** Corroboration status of the underlying claim */
  corroboration: CorroborationStatus;

  /** Full provenance chain */
  provenance: RuntimeProvenance;
}

// ============================================================
// RUNTIME CLASSIFICATION MODEL
// ============================================================

/**
 * AMath Runtime Classification
 * 
 * Runtime Layer → Policy Layer → Evidence Layer → Presentation Layer
 * 
 * Meaning:
 *   presentation never decides truth
 *   policy never invents evidence
 *   runtime never claims external certainty
 */
export type RuntimeLayer = 'runtime' | 'policy' | 'evidence' | 'presentation' | 'corroboration';

/**
 * Layer Responsibility Matrix
 */
export interface LayerResponsibility {
  layer: RuntimeLayer;
  responsibility: string;
  canDecideTruth: boolean;
  canInventEvidence: boolean;
  canClaimExternalCertainty: boolean;
}

export const LAYER_RESPONSIBILITIES: LayerResponsibility[] = [
  { layer: 'runtime', responsibility: 'Software truth', canDecideTruth: true, canInventEvidence: false, canClaimExternalCertainty: false },
  { layer: 'policy', responsibility: 'Deterministic decisions', canDecideTruth: false, canInventEvidence: false, canClaimExternalCertainty: false },
  { layer: 'evidence', responsibility: 'External validation', canDecideTruth: false, canInventEvidence: false, canClaimExternalCertainty: true },
  { layer: 'presentation', responsibility: 'Visualization only', canDecideTruth: false, canInventEvidence: false, canClaimExternalCertainty: false },
  { layer: 'corroboration', responsibility: 'Confidence boundary', canDecideTruth: false, canInventEvidence: false, canClaimExternalCertainty: false },
];

// ============================================================
// OBSERVED VS INTERPRETATION
// ============================================================

/**
 * Observed Runtime Facts
 * 
 * Examples:
 *   18 API endpoints responded successfully
 *   Build completed without export errors
 *   Receipt pipeline executed
 *   Topology engine returned route71
 */
export interface ObservedFact {
  id: string;
  observation: string;
  timestamp: string;
  source: 'build' | 'api' | 'runtime' | 'topology';
  metric?: number;
}

/**
 * Interpretation Layer
 * 
 * Examples:
 *   Operationally stable
 *   Ready for deployment
 *   Awaiting external corroboration
 * 
 * This prevents runtime logs from becoming narrative assertions.
 */
export interface Interpretation {
  id: string;
  statement: string;
  basedOn: string[]; // IDs of ObservedFacts
  confidence: 'high' | 'medium' | 'low';
  requiresCorroboration: boolean;
}

// ============================================================
// HARDENED CLOSED LOOP
// ============================================================

/**
 * Hardened Closed Loop Stages
 * 
 * Input → Validation → Policy → Decision → Receipt → Provenance → Route → Visualization → Corroboration Layer
 * 
 * This guarantees deterministic lifecycle tracking.
 */
export type ClosedLoopStage =
  | 'input'
  | 'validation'
  | 'policy'
  | 'decision'
  | 'receipt'
  | 'provenance'
  | 'route'
  | 'visualization'
  | 'corroboration';

export interface ClosedLoopState {
  currentStage: ClosedLoopStage;
  completedStages: ClosedLoopStage[];
  timestamp: string;
  traceId: string;
}

// ============================================================
// PRODUCTION HARDENING SCORECARD
// ============================================================

export type HardeningStatus = 'Hardened' | 'Recommended' | 'Modular' | 'Pending' | 'Not Started';

export interface HardeningCapability {
  capability: string;
  status: HardeningStatus;
  description: string;
  verifiedAt?: string;
}

export const PRODUCTION_SCORECARD: HardeningCapability[] = [
  { capability: 'Barrel Split', status: 'Hardened', description: 'client.ts / server.ts / index.ts separation' },
  { capability: 'Static Export Safety', status: 'Hardened', description: 'SSR-safe patterns enforced' },
  { capability: 'Hydration Guards', status: 'Hardened', description: 'Mounted guards on client components' },
  { capability: 'Runtime Provenance', status: 'Hardened', description: 'All receipts carry provenance' },
  { capability: 'Corroboration Layer', status: 'Hardened', description: 'All claims carry corroboration status' },
  { capability: 'Closed Loop Receipts', status: 'Hardened', description: 'ReceiptV2 with provenance chain' },
  { capability: 'API Determinism', status: 'Hardened', description: 'Deterministic decision functions' },
  { capability: 'Accessibility Runtime', status: 'Modular', description: 'Independent accessibility layer' },
];

// ============================================================
// FINAL HARDENED INVARIANT
// ============================================================

/**
 * Runtime confirms execution.
 * Evidence confirms reality.
 * Visualization reflects classification.
 * 
 * This creates a production-safe architecture where:
 *   software behavior is measurable
 *   claims are bounded
 *   trust is layered
 *   outputs are auditable
 */
export const HARDENED_INVARIANT = {
  runtime: 'confirms execution',
  evidence: 'confirms reality',
  visualization: 'reflects classification',
} as const;
